#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "Off | get stat for xdebug cli configuration file"
  ansible.builtin.stat:
    path: "/etc/php/{{ php_version_number }}/cli/conf.d/20-xdebug.ini"
  register: php_xdebug_cli_config_obj

- name: "Off | get stat for xdebug fpm configuration file"
  ansible.builtin.stat:
    path: "/etc/php/{{ php_version_number }}/fpm/conf.d/20-xdebug.ini"
  register: php_xdebug_fpm_config_obj

- name: "Off | delete xdebug cli configuration symlink if exists"
  ansible.builtin.file:
    path: "/etc/php/{{ php_version_number }}/cli/conf.d/20-xdebug.ini"
    state: absent
  when: php_xdebug_cli_config_obj.stat is defined and php_xdebug_cli_config_obj.stat.islnk is defined
  become: true

- name: "Off | delete xdebug fpm configuration symlink if exists"
  ansible.builtin.file:
    path: "/etc/php/{{ php_version_number }}/fpm/conf.d/20-xdebug.ini"
    state: absent
  when: php_xdebug_fpm_config_obj.stat is defined and php_xdebug_fpm_config_obj.stat.islnk is defined
  notify: "systemd | php{{ php_version_number }}-fpm | restarted"
  become: true
