##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: debug current_mysql_service
  ansible.builtin.debug:
    var: current_mysql_service

- name: install base packages
  ansible.builtin.apt:
    name: "{{ mysql_base_packages }}"
    state: present
  become: true
  loop_control:
    loop_var: mysql_base_packages
  loop:
    - "mysql-client"
    - "python3-pymysql"

- name: "create basic directories"
  ansible.builtin.file:
    path: "{{ current_mysql_base_directory }}"
    owner: "{{ current_user }}"
    group: "{{ current_group }}"
    mode: "0755"
    state: directory
  become: true
  with_items:
    - "{{ current_mysql_service.configuration.base_path }}"
    - "{{ current_mysql_service.configuration.base_path }}/user"
    - "{{ current_mysql_service.configuration.base_path }}/etc"
    - "{{ current_mysql_service.configuration.base_path }}/etc/conf.d"
  loop_control:
    loop_var: current_mysql_base_directory

- name: "Pull vsh-{{ current_mysql_service.canonical }} image"
  containers.podman.podman_image:
    name: "{{ current_mysql_service.configuration.docker_image }}"
    pull: true
    state: present

- name: "provide .my.cnf configuration file"
  ansible.builtin.template:
    src: "{{ current_mysql_service.canonical }}/.my.cnf.j2"
    dest: "{{ current_mysql_service.configuration.base_path }}/user/.my.cnf"
    mode: "0644"

- name: "provide my.cnf configuration file"
  ansible.builtin.template:
    src: "{{ current_mysql_service.canonical }}/my.cnf.j2"
    dest: "{{ current_mysql_service.configuration.base_path }}/etc/my.cnf"
    mode: "0644"
  notify: "systemd | vsh-mysql | restarted"

- name: "provide mysqld.cnf configuration file"
  ansible.builtin.template:
    src: "{{ current_mysql_service.canonical }}/mysqld.cnf.j2"
    dest: "{{ current_mysql_service.configuration.base_path }}/etc/conf.d/mysqld.cnf"
    owner: "{{ current_user }}"
    group: "{{ current_group }}"
    mode: "0644"
  notify: "systemd | vsh-mysql | restarted"

- name: "ensure user systemd directory exists"
  ansible.builtin.file:
    path: "{{ current_home }}/.config/systemd/user"
    state: directory
    mode: "0755"

- name: "provide vsh-{{ current_mysql_service.canonical }} systemd unit file"
  ansible.builtin.template:
    src: "systemd/mysql.service.j2"
    dest: "{{ current_home }}/.config/systemd/user/{{ current_mysql_service.service.name }}.service"
    owner: "{{ current_user }}"
    group: "{{ current_group }}"
    mode: "0644"
  notify: "systemd | vsh-mysql | restarted"

- name: "provide vsh-{{ current_mysql_service.canonical }} mysql client"
  ansible.builtin.template:
    src: "wrapper/mysql.j2"
    dest: "/usr/local/bin/mysql{{ current_mysql_service.version }}"
    owner: root
    group: root
    mode: "0755"
  become: true

- name: "provide mysqldump{{ current_mysql_service.version }} client"
  ansible.builtin.template:
    src: "wrapper/mysqldump.j2"
    dest: "/usr/local/bin/mysqldump{{ current_mysql_service.version }}"
    owner: root
    group: root
    mode: "0755"
  become: true

- name: "provide mysqladmin{{ current_mysql_service.version }} client"
  ansible.builtin.template:
    src: "wrapper/mysqladmin.j2"
    dest: "/usr/local/bin/mysqladmin{{ current_mysql_service.version }}"
    owner: root
    group: root
    mode: "0755"
  become: true

- name: "Ensure vsh-{{ current_mysql_service.canonical }} is started"
  ansible.builtin.systemd:
    name: "{{ current_mysql_service.service.name }}"
    state: started
    daemon_reload: true
    scope: user

- name: Test MySQL connection and get info
  community.mysql.mysql_info:
    login_host: "127.0.0.1"
    login_port: "{{ current_mysql_service.configuration.ports.mysql }}"
    login_user: "root"
    login_password: "{{ current_mysql_service.configuration.default_root_password }}"
  register: mysql_status
  until: mysql_status is succeeded
  retries: 30
  delay: 3

- name: Stop vsh-{{ current_mysql_service.canonical }} service after installation
  when: mysql_status is succeeded
  ansible.builtin.systemd:
    name: "{{ current_mysql_service.service.name }}"
    state: stopped
    scope: "{{ current_mysql_service.service.scope }}"

- name: "Mark vsh-{{ current_mysql_service.canonical }} as installed in the services file"
  vsh_bundle_state:
    action: "add_installed"
    canonical_names: "{{ current_mysql_service.canonical }}"
