##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- block:
    - name: "Ensure that vsh-{{ current_mysql_service.canonical }} container is stopped"
      ansible.builtin.systemd:
        name: "{{ current_mysql_service.service.name }}"
        state: stopped
        daemon_reload: true
        scope: "{{ current_mysql_service.service.scope }}"
      ignore_errors: true

    - name: "Remove vsh-{{ current_mysql_service.canonical }} container"
      containers.podman.podman_container:
        name: "{{ current_mysql_service.canonical }}"
        state: absent

    - name: "Remove vsh-{{ current_mysql_service.canonical }} volume"
      containers.podman.podman_volume:
        name: "vsh-{{ current_mysql_service.canonical }}-data"
        state: absent
      when: "'--purge' in valet_cli_opts"

    - name: "Remove vsh-{{ current_mysql_service.canonical }} systemd service"
      ansible.builtin.file:
        path: "{{ current_home }}/.config/systemd/user/{{ current_mysql_service.service.name }}.service"
        state: absent

    - name: "Remove vsh-{{ current_mysql_service.canonical }} default.target.wants symlink"
      ansible.builtin.file:
        path: "{{ current_home }}/.config/systemd/user/default.target.wants/{{ current_mysql_service.service.name }}.service"
        state: absent

    - name: "Remove vsh-{{ current_mysql_service.canonical }} configurations"
      ansible.builtin.file:
        path: "{{ current_mysql_service.configuration.base_path }}"
        state: absent

    - name: "Remove vsh-{{ current_mysql_service.canonical }} image"
      containers.podman.podman_image:
        name: "{{ current_mysql_service.configuration.docker_image }}"
        state: absent
        force: true
      when: "'--purge' in valet_cli_opts"

    - name: "Remove vsh-{{ current_mysql_service.canonical }} from installed services"
      vsh_bundle_state:
        action: "uninstalled"
        canonical_names: "{{ current_mysql_service.canonical }}"
