---

service:
  name:
    ubuntu: "vsh-mariadb106"
    mac: "vsh-mariadb106"
  scope:
    ubuntu: "user"
    mac: "user"
  provider:
    ubuntu: "systemd"
    mac: "container"

configuration:
  docker_image: "docker.io/library/mariadb:10.6"
  limits:
    memory: "4g"
    cpus: "2"
  ports:
    tcp: 3319
  base_path: "/usr/local/valet-sh/packages/mariadb106"
  default_root_password: "root"
  default_user: "mysql"
  default_group: "mysql"
