---

service:
  name:
    ubuntu: "vsh-mariadb118"
    mac: "vsh-mariadb118"
  scope:
    ubuntu: "user"
    mac: "user"
  provider:
    ubuntu: "systemd"
    mac: "container"

configuration:
  docker_image: "docker.io/library/mariadb:11.8"
  ports:
    mariadb: 3333
  base_path: "/usr/local/valet-sh/packages/mariadb118"
  default_root_password: "root"
  default_user: "mysql"
  default_group: "mysql"
