---

service:
  name:
    ubuntu: "vsh-mariadb123"
    mac: "vsh-mariadb123"
  scope:
    ubuntu: "user"
    mac: "user"
  provider:
    ubuntu: "systemd"
    mac: "container"

configuration:
  docker_image: "docker.io/library/mariadb:12.3"
  ports:
    tcp: 3337
  base_path: "/usr/local/valet-sh/packages/mariadb123"
  default_root_password: "root"
  default_user: "mysql"
  default_group: "mysql"
