---

service:
  name:
    ubuntu: "vsh-mailhog"
    mac: "vsh-mailhog"
  scope:
    ubuntu: "user"
    mac: "user"

configuration:
  docker_image: "docker.io/mailhog/mailhog:latest"
  ports:
    http: 8025
    smtp: 1025
