##
#   Copyright 2022 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "actions » partials » switch-target-db-host | resolve default database engine for family 'database'"
  ansible.builtin.set_fact:
    valet_db_canonical_name: "{{ (lookup('ansible.builtin.file', '/usr/local/valet-sh/etc/bundles.yml') | from_yaml).bundles.services.defaults.database }}"
  when: valet_db_canonical_name is not defined

- name: "actions » partials » switch-target-db-host | fail when no default database engine for family 'database' could be resolved"
  ansible.builtin.fail:
    msg: "no default database engine for family 'database' could be resolved"
  when: valet_db_canonical_name is not defined

- name: "actions » partials » switch-target-db-host | resolve {{ valet_db_canonical_name }} service"
  vsh_bundle_resolver:
    name: "{{ valet_db_canonical_name }}"
    current_os: "{{ current_os }}"
  register: database_service

- name: "actions » partials » switch-target-db-host | derive config file, client binary and connection info"
  ansible.builtin.set_fact:
    valet_db_mysql_target_config_file: "{{ database_service.services[0].configuration.base_path }}/user/.my.cnf"
    valet_db_mysql_client_binary: "{{ database_service.services[0].name }}"
    valet_db_mysql_port: "{{ database_service.services[0].configuration.ports.tcp }}"
