---

service:
  name:
    ubuntu: "vsh-rabbitmq-server"
    mac: "vsh-rabbitmq"
  scope:
    ubuntu: "user"
    mac: "user"

configuration:
  docker_image: "docker.io/rabbitmq/rabbitmq:3.12.14-management"
  ports:
    http: 15672
    amqp: 5672
