---

service:
  name:
    ubuntu: "vsh-mailpit"
    mac: "vsh-mailpit"
  scope:
    ubuntu: "user"
    mac: "user"
  provider:
    ubuntu: "systemd"
    mac: "container"

configuration:
  docker_image: "docker.io/axllent/mailpit:latest"
  limits:
    memory: "1g"
    cpus: "1"
  ports:
    http: 8025
    smtp: 1025
