##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

# @Fixme possible permission issues?!
- name: "ensure nginx is installed"
  homebrew:
    name: nginx
    state: absent

#- name: "ensure nginx is installed"
#  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} install nginx"

- name: Generate dhparams file
  ansible.builtin.shell: "openssl dhparam -out {{ nginx_dhparams_file }} {{ nginx_dhparams_keysize }}"
  args:
    creates: "{{ nginx_dhparams_file }}"

- name: "ensure /opt/homebrew/etc/nginx/nginx.conf is absent"
  file:
    path: "/opt/homebrew/etc/nginx/nginx.conf"
    state: absent

- name: "ensure '/opt/homebrew/etc/nginx/conf.d' is absent"
  ansible.builtin.file:
    path: "/opt/homebrew/etc/nginx/conf.d"
    state: absent

- name: Create nginx stream.d dir
  ansible.builtin.file:
    path: "/opt/homebrew/etc/nginx/stream.d"
    state: absent

- name: "ensure vhost directory '{{ valet_sh_default_vhost_root }}' exists"
  ansible.builtin.file:
    path: "{{ valet_sh_default_vhost_root }}"
    state: absent
  become: true


