##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "ensure nginx is stopped (running as root) (using homebrew)"
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin_sudo }} services stop nginx"
  failed_when: false

- name: "fix ownership of nginx keg directory"
  ansible.builtin.file:
    path: "/opt/homebrew/Cellar/nginx"
    state: directory
    recurse: true
    owner: "{{ current_user }}"
  become: true

- name: "ensure nginx is uninstalled"
  homebrew:
    name: nginx
    state: absent

- name: "ensure nginx related files and directories are absent"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  become: true
  loop:
    - "/opt/homebrew/etc/nginx/stream.d"
    - "/opt/homebrew/etc/nginx/conf.d"
    - "{{ valet_sh_default_vhost_root }}"
    - "/opt/homebrew/etc/nginx/"
    - "/opt/homebrew/var/log/nginx"

- name: "Remove nginx from installed services"
  vsh_bundle_state:
    action: "uninstalled"
    canonical_names: "nginx"
