##
#   Copyright 2024 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "Ensure openjdk17 is installed"
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - openjdk-17-jre
      - openjdk-17-jdk
  become: true

- name: "Ensure {{ opensearch_pid_path }} is created"
  ansible.builtin.file:
    path: "{{ opensearch_pid_path }}"
    owner: "{{ current_user }}"
    group: "{{ current_group }}"
    mode: '0755'
    state: directory
  become: true

- name: "Validate version"
  ansible.builtin.fail:
    msg: "'{{ package_name }}' is not available"
  when: package_name not in valet_sh.services.opensearch.variants

- name: "Include 'install-{{ package_name }}.yml'"
  ansible.builtin.include_tasks: "install-{{ package_name }}.yml"
