##
#   Copyright 2023 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "Include 'partials/check-db-name-var.yml'"
  ansible.builtin.include_tasks: partials/check-db-name-var.yml

- name: "Actions » import | override 'valet_db_name' variable if db name argument was given"
  ansible.builtin.set_fact:
    valet_db_name: "{{ valet_arg2 }}"
  when: valet_arg2 | length > 0

- name: "Actions » import | fail when no filename was given"
  ansible.builtin.fail:
    msg: "no filename was given"
  when: valet_arg1 | length == 0

- name: "Actions » import | set filename from args"
  ansible.builtin.set_fact:
    valet_db_filename: "{{ valet_arg1 }}"

- name: "Actions » import | set valet_db_file var"
  ansible.builtin.set_fact:
    valet_db_file: "{{ valet_db_filename }}"
  when: valet_db_filename[0]  == "/"

- name: "Actions » import | add path to 'valet_db_file' if it is not already an absolute path"
  ansible.builtin.set_fact:
    valet_db_file: "{{ valet_current_path }}/{{ valet_db_filename }}"
  when: valet_db_file is not defined

- name: "Actions » import | Import database {{ valet_db_file }} into database '{{ valet_db_name }}'"
  ansible.builtin.mysql_db:
    state: import
    config_file: "{{ valet_db_mysql_target_config_file }}"
    config_overrides_defaults: true
    name: "{{ valet_db_name }}"
    target: "{{ valet_db_file }}"
