##
#   Copyright 2021 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---


mariadb_server_default:
  base_path: "{{ valet_packages_path }}/mariadb"
  base_packages:
    - "mariad-client"
    - "python3-pymysql"
  default_root_password: "root"
  default_user: mysql
  default_group: mysql

mariadb_server_ubuntu_noble:
  base_path: "{{ valet_packages_path }}/mariadb"
  base_packages:
    - "mariadb-client"
    - "python3-pymysql"
  default_root_password: "root"
  default_user: mysql
  default_group: mysql

mariadb_server: "{{ lookup('vars', 'mariadb_server_' + current_os + '_' + os_codename, default=mariadb_server_default) }}"

mariadb_server_default_root_password: "root"

mariadb_server_104:
  image: "docker.io/library/mariadb:10.4"
  port: 3317
mariadb_server_106:
  image: "docker.io/library/mariadb:10.6"
  port: 3319
mariadb_server_114:
  image: "docker.io/library/mariadb:11.4"
  port: 3329
