##
#   Copyright 2023 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

valet_sh_service_internal_action: false
valet_sh_service_allowed_actions_default:
  - disable
  - enable
  - restart
  - start
  - stop
  - default
  - list
valet_sh_service_allowed_actions: "{{ lookup('vars', 'valet_sh_service_allowed_actions' + '_' + current_os, default=valet_sh_service_allowed_actions_default) }}"

valet_sh_service_definitions:
  php:
    display_name: "PHP"
    default_version: "7.3"
    versions: ["5.6", "7.0", "7.1", "7.2", "7.3", "7.4", "8.0", "8.1", "8.2", "8.3", "8.4"]
    role_name: "php"
    defaultable: true

  elasticsearch:
    display_name: "Elasticsearch"
    versions: ["1", "2", "5", "6", "7", "8"]
    default_version: "6"
    role_name: "elasticsearch"
    defaultable: true

  opensearch:
    display_name: "OpenSearch"
    versions: ["1", "2"]
    default_version: "2"
    role_name: "opensearch"
    defaultable: true

  mysql:
    display_name: "MySQL"
    versions: ["5.7", "8.0", "8.4"]
    default_version: "5.7"
    role_name: "mysql-community-server"
    defaultable: true

  mariadb:
    display_name: "MariaDB"
    versions: ["10.4", "10.6", "11.4"]
    default_version: "10.4"
    role_name: "mariadb-server"
    defaultable: true

  nginx:
    display_name: "Nginx"
    role_name: "nginx"
    defaultable: false

  redis:
    display_name: "Redis"
    versions: ["default"]
    default_version: "default"
    role_name: "redis"
    defaultable: false

  rabbitmq:
    display_name: "RabbitMQ"
    versions: ["default"]
    default_version: "default"
    role_name: "rabbitmq"
    defaultable: false

  dnsmasq:
    display_name: "Dnsmasq"
    role_name: "dnsmasq"
    defaultable: false

  mailhog:
    display_name: "MailHog"
    versions: ["default"]
    default_version: "default"
    role_name: "mailhog"
    defaultable: false

valet_sh_service_default_states:
  enabled_services:
    - "nginx"
    - "php73"
    - "redis"
    - "mysql57"
    - "elasticsearch6"
  disabled_services:
    - "rabbitmq"

valet_sh_service_default_states_mac:
  enabled_services:
    - "nginx"
    - "php73"
    - "redis"
    - "mysql57"
    - "elasticsearch6"
  disabled_services:
    - "rabbitmq"
