##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

ansible_managed: This file is managed by valet.sh , all changes will be lost.

valet_sh_homebrew_prefix_default: ""
valet_sh_homebrew_prefix_mac: "/opt/homebrew"
valet_sh_homebrew_prefix: "{{ lookup('vars', 'valet_sh_homebrew_prefix' + '_' + current_os, default=valet_sh_homebrew_prefix_default) }}"

valet_sh_prefix_default: ""
valet_sh_prefix_mac: "/opt/homebrew"
valet_sh_prefix: "{{ lookup('vars', 'valet_sh_prefix' + '_' + current_os, default=valet_sh_prefix_default) }}"

valet_base_path_default: "/usr/local/valet-sh"
valet_base_path: "{{ lookup('vars', 'valet_base_path' + '_' + current_os, default=valet_base_path_default) }}"

valet_dist_path_default: "{{ valet_base_path }}/valet-sh"
valet_dist_path: "{{ lookup('vars', 'valet_dist_path' + '_' + current_os, default=valet_dist_path_default) }}"

valet_etc_path_default: "{{ valet_base_path }}/etc"
valet_etc_path: "{{ lookup('vars', 'valet_etc_path' + '_' + current_os, default=valet_etc_path_default) }}"

valet_packages_path_default: "{{ valet_base_path }}/packages"
valet_packages_path: "{{ lookup('vars', 'valet_packages_path' + '_' + current_os, default=valet_packages_path_default) }}"

valet_overwrites_path_default: "{{ valet_etc_path }}/overwrites"
valet_overwrites_path: "{{ lookup('vars', 'valet_overwrites_path' + '_' + current_os, default=valet_overwrites_path_default) }}"

valet_sh_homebrew_bin: "/opt/homebrew/bin/brew"
valet_sh_homebrew_bin_sudo: "sudo /opt/homebrew/bin/brew"

development_tld_default: test
development_tld: "{{ lookup('vars', 'development_tld' + '_' + current_os, default=development_tld_default) }}"

vsh_service_tld_default: vsh
vsh_service_tld: "{{ lookup('vars', 'vsh_service_tld' + '_' + current_os, default=vsh_service_tld_default) }}"


valet_sh_sudo_commands:
  - "{{ valet_sh_homebrew_bin }} services start nginx"
  - "{{ valet_sh_homebrew_bin }} services stop nginx"
  - "{{ valet_sh_homebrew_bin }} services restart nginx"
  - "{{ valet_sh_homebrew_bin }} services stop dnsmasq"

valet_etc_links_file: "{{ valet_etc_path }}/links.yml"

valet_etc_config_file: "{{ valet_etc_path }}/config.yml"

valet_etc_services_file: "{{ valet_etc_path }}/bundles.yml"

valet_etc_revision_filename: "REVISION"
valet_etc_revision_file: "{{ valet_etc_path }}/{{ valet_etc_revision_filename }}"

valet_sh_filename: ".valet-sh.yml"

valet_sh_hub_read_user: "read"

valet_base_dirs:
  - "{{ valet_base_path }}"
  - "{{ valet_etc_path }}"
  - "{{ valet_packages_path }}"
  - "{{ valet_overwrites_path }}"

valet_links_stub:
  valet_links:
    links_index: []
    links: []
valet_sh_default_node_version: 16

valet_sh_default_vhost_domain: "sites"
valet_sh_default_vhost_root: "/usr/local/valet-sh/default-vhost"
