##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---


mysql_community_server_default:
  base_path: "{{ valet_packages_path }}/mysql"
  base_packages:
    - "libaio1"
    - "libncurses5"
    - "libtinfo5"
    - "python3-pymysql"
  default_root_password: "root"
  default_user: mysql
  default_group: mysql


mysql_community_server_ubuntu_noble:
  base_path: "{{ valet_packages_path }}/mysql"
  base_packages:
    - "libaio1t64"
    - "libncurses6"
    - "libtinfo6"
    - "python3-pymysql"
  default_root_password: "root"
  default_user: mysql
  default_group: mysql

mysql_community_server: "{{ lookup('vars', 'mysql_community_server_' + current_os + '_' + os_codename, default=mysql_community_server_default) }}"

mysql_community_server_default_root_password: "root"

mysql_community_server_57:
  package_url: "https://mirror.valet.sh/mysql-5.7.44-linux-glibc2.12-x86_64.tar.gz"
  package_signature: 798ff0a14cdc1ab259f8a3b6a7f683403e9bbaa85957d82e5370f82b27ba6805
  port: 3307

mysql_community_server_80:
  package_url: "https://mirror.valet.sh/mysql-8.0.36-linux-glibc2.17-x86_64.tar.xz"
  package_signature: 280c5106644948468f0e51c4d3397f318e49e332c74a79630d085dec62db03ee
  port: 3308

mysql_community_server_84:
  package_url: "https://mirror.valet.sh/mysql-8.4.4-linux-glibc2.28-x86_64.tar.xz"
  package_signature: b305974fb1bca83609a257d3da5c09ce429929b786e2cd9c15ecd809fd16364f
  port: 3309