##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

valet_sh_default_project_name: "{{ valet_sh_config.hub_project }}"
#valet_sh_default_project_branch: "master"
valet_sh_project_hub_fqdn: "gitlab.{{ valet_project_name }}.{{ valet_sh_config.hub_domain }}"

valet_sh_default_project_git_clone_command: "ssh://git@{{ valet_sh_project_hub_fqdn }}:{{ valet_sh_config.hub_gitlab_ssh_port }}/{{ valet_project_name }}/{{ valet_sh_default_project_name }}.git"

valet_sh_service_rabbitmq_user: admin
valet_sh_service_rabbitmq_password: admin

valet_sh_service_mysql_charset: utf8
valet_sh_service_mysql_collation_string_mysql80: 'SET default_collation_for_utf8mb4 = "utf8mb4_general_ci";'

valet_sh_service_mysql_host_presets:
  mysql57: "127.0.0.1:3307"
  mysql80: "127.0.0.1:3308"
  mysql84: "127.0.0.1:3309"
  mariadb104: "127.0.0.1:3317"
  mariadb106: "127.0.0.1:3319"
  mariadb1011: "127.0.0.1:3324"
  mariadb114: "127.0.0.1:3329"


valet_sh_aem_local_cache_dirname: ".aemcache"
valet_sh_aem_local_cache_dir: "{{ current_home }}/{{ valet_sh_aem_local_cache_dirname }}"
valet_sh_aem_sdk_local_cache_dir: "{{ valet_sh_aem_local_cache_dir }}/aem-sdk"


aem_adobe_universal_service_nodejs_binary_url_default: https://nodejs.org/dist/v22.12.0/node-v22.12.0-linux-x64.tar.xz
aem_adobe_universal_service_nodejs_binary_url_mac_x86: https://nodejs.org/dist/v22.12.0/node-v22.12.0-darwin-x64.tar.gz
aem_adobe_universal_service_nodejs_binary_url_mac_arm64: https://nodejs.org/dist/v22.12.0/node-v22.12.0-darwin-arm64.tar.gz
aem_adobe_universal_service_nodejs_binary_url: "{{ lookup('vars', 'aem_adobe_universal_service_nodejs_binary_url'+'_' + current_os + '_' + current_arch, default=aem_adobe_universal_service_nodejs_binary_url_default) }}"
aem_adobe_universal_service_vhost_server_name: adobe-universal-editor-service

aem_adobe_universal_service_remote_file_name: "{{ file_name }}"
aem_adobe_universal_service_remote_real_file_path: "{{ remote_dir }}/{{ aem_adobe_universal_service_remote_real_file_name }}"
