##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "systemd | vsh-redis | started"
  ansible.builtin.systemd:
    daemon_reload: true
    name: "vsh-{{ handler_current_service.canonical }}"
    state: started
    scope: "{{ handler_current_service.service.scope }}"

- name: "systemd | vsh-redis | stopped"
  ansible.builtin.systemd:
    daemon_reload: true
    name: "vsh-{{ handler_current_service.canonical }}"
    state: stopped
    scope: "{{ handler_current_service.service.scope }}"

- name: "systemd | vsh-redis | restarted"
  ansible.builtin.systemd:
    daemon_reload: true
    name: "vsh-{{ handler_current_service.canonical }}"
    state: restarted
    scope: "{{ handler_current_service.service.scope }}"


- name: "container | vsh-redis | started"
  apple_container:
    name: "vsh-{{ handler_current_service.canonical }}"
    state: started

- name: "container | vsh-redis | stopped"
  apple_container:
    name: "vsh-{{ handler_current_service.canonical }}"
    state: stopped

- name: "container | vsh-redis | restarted"
  apple_container:
    name: "vsh-{{ handler_current_service.canonical }}"
    state: restarted
