##
#   Copyright 2023 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: Systemd | redis-server | started
  ansible.builtin.systemd:
    name: redis-server
    state: started
  become: true

- name: Systemd | redis-server | stopped
  ansible.builtin.systemd:
    name: redis-server
    state: stopped
  become: true

- name: Systemd | redis-server | restarted
  ansible.builtin.systemd:
    name: redis-server
    state: restarted
  become: true

- name: Brew | redis | started
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services start redis"

- name: Brew | redis | stopped
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services stop redis"

- name: Brew | redis | restarted
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services restart redis"
