##
#   Copyright 2023 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "Templates » shopware6 | set 'shopware6_template_found' when type in .valet-sh.yml was set"
  ansible.builtin.set_fact:
    shopware6_template_found: true
  when:
    - valet_sh_project_vars is defined
    - valet_sh_project_vars.instance is defined
    - valet_sh_project_vars.instance.type is defined
    - valet_sh_project_vars.instance.type == "shopware6"

- name: "Templates » shopware6 | check for shopware6 project"
  ansible.builtin.stat:
    path: "{{ valet_current_path }}/custom/plugins"
  register: shopware6_checker_obj

- name: "Block"
  when: shopware6_checker_obj.stat.exists or shopware6_template_found|bool
  ansible.builtin.block:
    - name: "Templates » shopware6 | provide nginx vhost configuration for {{ link_name }}.{{ development_tld }}"
      ansible.builtin.template:
        src: "nginx/shopware6.conf.j2"
        dest: "/etc/nginx/conf.d/{{ link_name }}.{{ development_tld }}.conf"
        owner: root
        group: root
        mode: '0644'
      notify: systemd | nginx | restarted
      become: true

    - name: "Templates » shopware6 | set var 'template_found' when shopware6 instance was found"
      ansible.builtin.set_fact:
        template_found: true
        nginx_template: "Shopware 6"
