##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "actions » restart | fail when no service name was given"
  ansible.builtin.fail:
    msg: "no service name was given"
  when: service_item.service is not defined and not '--all' in valet_cli_opts

- name: "actions » restart | include sub-restart-all task when service name is all"
  ansible.builtin.include_tasks: "macos/actions/sub-restart-all.yml"
  when: "'--all' in valet_cli_opts"

- block:
    - name: "actions » restart | restart {{ service_item.service.name }} service (running as root) (using homebrew)"
      ansible.builtin.shell: "{{ valet_sh_homebrew_bin_sudo }} services restart {{ service_item.service.name }}"
      failed_when: false
      when: service_item.service.scope == 'system' and service_item.service.provider == 'homebrew'

    - name: "actions » restart | restart {{ service_item.service.name }} service (using homewbrew)"
      ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services restart {{ service_item.service.name }}"
      failed_when: false
      when: service_item.service.scope == 'user' and service_item.service.provider == 'homebrew'

    - name: "actions » restart | restart {{ service_item.service.name }} service (using container)"
      apple_container:
        name: "{{ service_item.service.name }}"
        state: restarted
      when: service_item.service.scope == 'user' and service_item.service.provider == 'container'
  when: "'--all' not in valet_cli_opts"
