#   Copyright 2023 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "Workflows » aem | check if instancebackup package '{{ valet_sh_aem_restore_current_packagename }}.zip'"
  ansible.builtin.stat:
    path: "{{ valet_sh_project_vars.hub.path }}/{{ valet_instancebackup_identifier }}/instance-backup/{{ valet_sh_aem_restore_current_packagename }}.zip"
  register: instancebackup_target_package_file_obj
  delegate_to: hub

- name: "Workflows » aem | fail when package '{{ valet_sh_aem_restore_current_packagename }}.zip' does not exist"
  ansible.builtin.fail:
    msg: "file '{{ valet_sh_aem_restore_current_packagename }}.zip' does not exist!"
  when: not instancebackup_target_package_file_obj.stat.exists

- name: "Workflows » aem | synchronize package '{{ valet_sh_aem_restore_current_packagename }}.zip'"
  ansible.builtin.shell: "rsync -aL -e 'ssh -p {{ valet_sh_hub_port }}' {{ valet_sh_hub_user }}@{{ valet_sh_hub_host }}:{{ valet_sh_project_vars.hub.path }}/{{ valet_instancebackup_identifier }}/{{ valet_sh_project_vars.instance.sync.groupname }}/{{ valet_sh_aem_restore_current_packagename }}.zip {{ valet_sh_aem_runtime_tmp_dir }}/"
  tags:
    - skip_ansible_lint
