##
#   Copyright 2023 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "ensure vsh-mysql57 is installed"
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} install vsh-mysql57"

- name: "provide .my.cnf configuration file"
  ansible.builtin.template:
    src: "{{ mysql57_template_dot_my }}"
    dest: "{{ current_home }}/.my5.7.cnf"
    mode: '0644'
  with_first_found:
    - "macos/mysql57/.my.cnf.j2"
    - "mysql57/.my.cnf.j2"
  loop_control:
    loop_var: mysql57_template_dot_my

- name: "provide mysql.cnf configuration file"
  ansible.builtin.template:
    src: "{{ mysql57_template_mysql }}"
    dest: "{{ valet_sh_prefix }}/etc/vsh-mysql57/conf.d/mysql.cnf"
    mode: '0644'
  with_first_found:
    - "macos/mysql57/mysql.cnf.j2"
    - "mysql57/mysql.cnf.j2"
  loop_control:
    loop_var: mysql57_template_mysql

- name: "provide mysqldump.cnf configuration file"
  ansible.builtin.template:
    src: "{{ mysql57_template_mysqldump }}"
    dest: "{{ valet_sh_prefix }}/etc/vsh-mysql57/conf.d/mysqldump.cnf"
    mode: '0644'
  with_first_found:
    - "macos/mysql57/mysqldump.cnf.j2"
    - "mysql57/mysqldump.cnf.j2"
  loop_control:
    loop_var: mysql57_template_mysqldump

- name: "provide mysqld.cnf configuration file"
  ansible.builtin.template:
    src: "{{ mysql57_template_mysqld }}"
    dest: "{{ valet_sh_prefix }}/etc/vsh-mysql57/conf.d/mysqld.cnf"
    mode: '0644'
  with_first_found:
    - "macos/mysql57/mysqld.cnf.j2"
    - "mysql57/mysqld.cnf.j2"
  loop_control:
    loop_var: mysql57_template_mysqld

- name: brew | vsh-mysql57 | restarted
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services restart vsh-mysql57"

- name: wait for mysql57 to start
  ansible.builtin.wait_for:
    port: 3307
    delay: 5

- name: Set root password
  ansible.builtin.mysql_user:
    login_host: 127.0.0.1
    login_port: "{{ mysql_community_server_57.port }}"
    login_user: root
    login_password: "{{ mysql_community_server_default_root_password }}"
    config_file: "/tmp/noexistent.cnf"
    name: "root"
    password: "{{ mysql_community_server_default_root_password }}"
    check_implicit_admin: true
    state: present
