##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "systemd | vsh-{{ current_mailhog_service.canonical }}| stopped"
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ current_mailhog_service.service.name }}"
    state: started
    scope: "{{ current_mailhog_service.service.scope }}"
  loop: "{{ vsh_resolver.services | selectattr('canonical', 'match', '^mailhog.*') }}"
  loop_control:
    loop_var: mailhog_item
  listen:: "systemd | vsh-mailhog | stopped"

- name: "systemd | vsh-{{ current_mailhog_service.canonical }}| started"
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ current_mailhog_service.service.name }}"
    state: stopped
    scope: "{{ current_mailhog_service.service.scope }}"
  loop: "{{ vsh_resolver.services | selectattr('canonical', 'match', '^mailhog.*') }}"
  loop_control:
    loop_var: mailhog_item
  listen:: "systemd | vsh-mailhog | started"

- name: "systemd | vsh-{{ current_mailhog_service.canonical }}| restarted"
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ current_mailhog_service.service.name }}"
    state: restarted
    scope: "{{ current_mailhog_service.service.scope }}"
  loop: "{{ vsh_resolver.services | selectattr('canonical', 'match', '^mailhog.*') }}"
  loop_control:
    loop_var: mailhog_item
  listen:: "systemd | vsh-mailhog | restarted"

- name: brew | mailhog | stopped
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services stop mailhog"
- name: brew | mailhog | started
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services start mailhog"
- name: brew | mailhog | restart
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services restart mailhog"
