##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: systemd | elasticsearch1 | started
  ansible.builtin.systemd:
    daemon_reload: true
    name: elasticsearch1
    state: started
    scope: user

- name: systemd | elasticsearch1 | stopped
  ansible.builtin.systemd:
    daemon_reload: true
    name: elasticsearch1
    state: stopped
    scope: user

- name: systemd | elasticsearch1 | restarted
  ansible.builtin.systemd:
    daemon_reload: true
    name: elasticsearch1
    state: restarted
    scope: user

- name: systemd | elasticsearch1 | reloaded
  ansible.builtin.systemd:
    daemon_reload: true
    name: elasticsearch1
    state: restarted
    scope: user

- name: systemd | elasticsearch2 | started
  ansible.builtin.systemd:
    daemon_reload: true
    name: elasticsearch2
    state: started
    scope: user

- name: systemd | elasticsearch2 | stopped
  ansible.builtin.systemd:
    daemon_reload: true
    name: elasticsearch2
    state: stopped
    scope: user

- name: systemd | elasticsearch2 | restarted
  ansible.builtin.systemd:
    daemon_reload: true
    name: elasticsearch2
    state: restarted
    scope: user

- name: systemd | elasticsearch2 | reloaded
  ansible.builtin.systemd:
    daemon_reload: true
    name: elasticsearch2
    state: restarted
    scope: user

- name: systemd | elasticsearch5 | started
  ansible.builtin.systemd:
    daemon_reload: true
    name: elasticsearch5
    state: started
    scope: user

- name: systemd | elasticsearch5 | stopped
  ansible.builtin.systemd:
    daemon_reload: true
    name: elasticsearch5
    state: stopped
    scope: user

- name: systemd | elasticsearch5 | restarted
  ansible.builtin.systemd:
    daemon_reload: true
    name: elasticsearch5
    state: restarted
    scope: user

- name: systemd | elasticsearch5 | reloaded
  ansible.builtin.systemd:
    daemon_reload: true
    name: elasticsearch5
    state: restarted
    scope: user


- name: systemd | elasticsearch6 | started
  ansible.builtin.systemd:
    daemon_reload: true
    name: elasticsearch6
    state: started
    scope: user

- name: systemd | elasticsearch6 | stopped
  systemd:
    daemon_reload: true
    name: elasticsearch6
    state: stopped
    scope: user

- name: systemd | elasticsearch6 | restarted
  ansible.builtin.systemd:
    daemon_reload: true
    name: elasticsearch6
    state: restarted
    scope: user

- name: systemd | elasticsearch6 | reloaded
  ansible.builtin.systemd:
    daemon_reload: true
    name: elasticsearch6
    state: restarted
    scope: user

- name: systemd | elasticsearch7 | started
  ansible.builtin.systemd:
    daemon_reload: true
    name: elasticsearch7
    state: started
    scope: user

- name: systemd | elasticsearch7 | stopped
  ansible.builtin.systemd:
    daemon_reload: true
    name: elasticsearch7
    state: stopped
    scope: user

- name: systemd | elasticsearch7 | restarted
  ansible.builtin.systemd:
    daemon_reload: true
    name: elasticsearch7
    state: restarted
    scope: user

- name: systemd | elasticsearch7 | reloaded
  ansible.builtin.systemd:
    daemon_reload: true
    name: elasticsearch7
    state: restarted
    scope: user

- name: systemd | elasticsearch8 | started
  ansible.builtin.systemd:
    daemon_reload: true
    name: elasticsearch8
    state: started
    scope: user

- name: systemd | elasticsearch8 | stopped
  ansible.builtin.systemd:
    daemon_reload: true
    name: elasticsearch8
    state: stopped
    scope: user

- name: systemd | elasticsearch8 | restarted
  ansible.builtin.systemd:
    daemon_reload: true
    name: elasticsearch8
    state: restarted
    scope: user

- name: systemd | elasticsearch8 | reloaded
  ansible.builtin.systemd:
    daemon_reload: true
    name: elasticsearch8
    state: restarted
    scope: user

- name: brew | vsh-elasticsearch5 | restarted
  shell: "{{ valet_sh_homebrew_bin }} services restart vsh-elasticsearch5"

- name: brew | vsh-elasticsearch6 | restarted
  shell: "{{ valet_sh_homebrew_bin }} services restart vsh-elasticsearch6"

- name: brew | vsh-elasticsearch7 | restarted
  shell: "{{ valet_sh_homebrew_bin }} services restart vsh-elasticsearch7"

- name: brew | vsh-elasticsearch8 | restarted
  shell: "{{ valet_sh_homebrew_bin }} services restart vsh-elasticsearch8"
