---

service:
  name:
    ubuntu: "vsh-mysql57"
    mac: "vsh-mysql57"
  scope:
    ubuntu: "user"
    mac: "user"
  provider:
    ubuntu: "systemd"
    mac: "container"

configuration:
  docker_image: "docker.io/library/mysql:5.7"
  ports:
    tcp: 3307
  base_path: "/usr/local/valet-sh/packages/mysql57"
  default_root_password: "root"
  default_user: "mysql"
  default_group: "mysql"
