##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "Pull vsh-{{ current_service.canonical }} image"
  containers.podman.podman_image:
    name: "{{ current_service.configuration.docker_image }}"
    pull: true
    state: present

- name: Debug vsh-{{ current_service.canonical }}
  ansible.builtin.debug:
    msg: "vsh-{{ current_service.canonical }}"

- name: "Create vsh-{{ current_service.canonical }} config directory"
  ansible.builtin.file:
    path: "{{ current_service.configuration.base_path }}/config"
    owner: "{{ current_user }}"
    group: "{{ current_group }}"
    mode: "0755"
    state: directory

- name: "provide vsh-{{ current_service.canonical }} configuration"
  ansible.builtin.template:
    src: "config/{{ current_service.canonical }}.yml.j2"
    dest: "{{ current_service.configuration.base_path }}/config/elasticsearch.yml"
    mode: "0644"
  notify: "systemd | vsh-elasticsearch | restarted"

- name: "ensure user systemd directory exists"
  ansible.builtin.file:
    path: "{{ current_home }}/.config/systemd/user"
    state: directory
    mode: "0755"

- name: "Provide systemd service for vsh-{{ current_service.canonical }} container"
  ansible.builtin.template:
    src: "systemd/elasticsearch.service.j2"
    dest: "{{ current_home }}/.config/systemd/user/{{ current_service.service.name }}.service"
    owner: "{{ current_user }}"
    group: "{{ current_group }}"
    mode: "0644"
  notify: "systemd | vsh-elasticsearch | started"

- name: "Ensure vsh-{{ current_service.canonical }} is started"
  ansible.builtin.systemd:
    name: "{{ current_service.service.name }}"
    state: started
    daemon_reload: true
    scope: "{{ current_service.service.scope }}"

- name: "Wait for vsh-{{ current_service.canonical }} to be ready"
  ansible.builtin.uri:
    url: "http://localhost:{{ current_service.configuration.ports.http }}/_cluster/health"
    method: GET
    status_code: 200
  register: result
  until: result.status == 200
  retries: 15
  delay: 3

- name: "list installed plugins"
  containers.podman.podman_container_exec:
    name: "vsh-{{ current_service.canonical }}"
    command: "{{ current_service.configuration.plugins.list_command }}"
  register: installed_plugins

- name: "install plugins"
  containers.podman.podman_container_exec:
    name: "vsh-{{ current_service.canonical }}"
    command: "{{ current_service.configuration.plugins.install_command }} {{ current_elasticsearch_plugin.name }}"
  with_items: "{{ current_service.configuration.plugins.default_plugins }}"
  loop_control:
    loop_var: current_elasticsearch_plugin
  notify: "systemd | vsh-elasticsearch | restarted"
  when:
    - current_elasticsearch_plugin.name not in installed_plugins.stdout_lines
    - current_elasticsearch_plugin.url is not defined
    - "current_elasticsearch_plugin.name not in ' '.join(installed_plugins.stdout_lines | map('regex_replace', '^\\s*-\\s*', ''))"

- name: "install plugins from url"
  containers.podman.podman_container_exec:
    name: "vsh-{{ current_service.canonical }}"
    command: "{{ current_service.configuration.plugins.install_command }} {{ current_elasticsearch_plugin.name }} --url {{ current_elasticsearch_plugin.url }}"
  with_items: "{{ current_service.configuration.plugins.default_plugins }}"
  loop_control:
    loop_var: current_elasticsearch_plugin
  notify: "systemd | vsh-elasticsearch | restarted"
  when:
    - current_elasticsearch_plugin.name not in installed_plugins.stdout_lines
    - current_elasticsearch_plugin.url is defined
    - "current_elasticsearch_plugin.name not in ' '.join(installed_plugins.stdout_lines | map('regex_replace', '^\\s*-\\s*', ''))"

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers

- name: "Get desired state of vsh-{{ current_service.canonical }} from services file"
  vsh_bundle_service_state_info:
    name: "{{ current_service.canonical }}"
  register: current_service_state

- name: "If desired state is unknown, set it to enabled"
  vsh_bundle_state:
    action: "initialize_empty"
    canonical_names: "{{ current_service.canonical }}"
  when: current_service_state.state == "unknown"

- name: "Update current_service_state after initialization"
  ansible.builtin.set_fact:
    current_service_state: "{{ current_service_state | combine({'state': 'enabled'}) }}"
  when: current_service_state.state == "unknown"

- name: "Set vsh-{{ current_service.canonical }} container state"
  ansible.builtin.systemd:
    name: "{{ current_service.service.name }}"
    state: "{{ 'started' if current_service_state.state == 'enabled' else 'stopped' }}"
    enabled: "{{ 'true' if current_service_state.state == 'enabled' else 'false' }}"
    scope: "{{ current_service.service.scope }}"

- name: "Mark vsh-{{ current_service.canonical }} as installed in the services file"
  vsh_bundle_state:
    action: "installed"
    canonical_names: "{{ current_service.canonical }}"
