##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "Set current_elasticsearch_service_handler_name"
  ansible.builtin.set_fact:
    current_elasticsearch_service_handler_name: "vsh-{{ current_elasticsearch_service.canonical }}"

- name: "get stats for dir {{ current_elasticsearch_service.configuration.base_path }}"
  ansible.builtin.stat:
    path: "{{ current_elasticsearch_service.configuration.base_path }}"
  register: current_elasticsearch_base_path_obj

- block:
    - name: "Pull vsh-{{ current_elasticsearch_service.canonical }} image"
      containers.podman.podman_image:
        name: "{{ current_elasticsearch_service.configuration.docker_image }}"
        pull: true
        state: present

    - name: Debug vsh-{{ current_elasticsearch_service.canonical }}
      ansible.builtin.debug:
        msg: "vsh-{{ current_elasticsearch_service.canonical }}"

    - name: "Create vsh-{{ current_elasticsearch_service.canonical }} config directory"
      ansible.builtin.file:
        path: "{{ current_elasticsearch_service.configuration.base_path }}/config"
        owner: "{{ current_user }}"
        group: "{{ current_group }}"
        mode: "0755"
        state: directory

    - name: "provide vsh-{{ current_elasticsearch_service.canonical }} configuration"
      ansible.builtin.template:
        src: "config/{{ current_elasticsearch_service.canonical }}.yml.j2"
        dest: "{{ current_elasticsearch_service.configuration.base_path }}/config/elasticsearch.yml"
        mode: "0644"
      notify: "systemd | vsh-elasticsearch | restarted"
      when: not current_elasticsearch_base_path_obj.stat.exists

    - name: "ensure user systemd directory exists"
      ansible.builtin.file:
        path: "{{ current_home }}/.config/systemd/user"
        state: directory
        mode: "0755"

    - name: "Provide systemd service for vsh-{{ current_elasticsearch_service.canonical }} container"
      ansible.builtin.template:
        src: "systemd/{{ current_elasticsearch_service.canonical }}.service.j2"
        dest: "{{ current_home }}/.config/systemd/user/{{ current_elasticsearch_service.service.name }}.service"
        owner: "{{ current_user }}"
        group: "{{ current_group }}"
        mode: "0644"
      notify: "systemd | vsh-elasticsearch | started"

    - name: "Ensure vsh-{{ current_elasticsearch_service.canonical }} is started"
      ansible.builtin.systemd:
        name: "{{ current_elasticsearch_service.service.name }}"
        state: started
        daemon_reload: true
        scope: "{{ current_elasticsearch_service.service.scope }}"

    - name: "Wait for vsh-{{ current_elasticsearch_service.canonical }} to be ready"
      ansible.builtin.uri:
        url: "http://localhost:{{ current_elasticsearch_service.configuration.ports.http }}/_cluster/health"
        method: GET
        status_code: 200
      register: result
      until: result.status == 200
      retries: 15
      delay: 3

    - name: "install plugins"
      containers.podman.podman_container_exec:
        name: "vsh-{{ current_elasticsearch_service.canonical }}"
        command: "{{ current_elasticsearch_service.configuration.plugins.install_command | replace('{{ name }}', current_elasticsearch_plugin) }}"
      with_items: "{{ current_elasticsearch_service.configuration.plugins.default_plugins }}"
      loop_control:
        loop_var: current_elasticsearch_plugin
      notify: "systemd | vsh-elasticsearch | restarted"
      when: not current_elasticsearch_base_path_obj.stat.exists

    - name: "Stop vsh-{{ current_elasticsearch_service.canonical }} container after plugin installation"
      ansible.builtin.systemd:
        name: "{{ current_elasticsearch_service.service.name }}"
        state: stopped
        scope: "{{ current_elasticsearch_service.service.scope }}"
