##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---
###########################
## start handle service states

- name: Debug valet_sh_newly_installed_services
  ansible.builtin.debug:
    var: valet_sh_newly_installed_services

- name: "internal-actions » handle | set valet_all_services from newly installed services"
  ansible.builtin.set_fact:
    valet_all_services: "{{ valet_sh_newly_installed_services | unique(attribute='name') }}"

- name: "internal-actions » handle | extract canonical names"
  ansible.builtin.set_fact:
    valet_canonical_names: "{{ valet_all_services | map(attribute='canonical') | list }}"

- name: "internal-actions » handle | set services as enabled using vsh_bundle_state module"
  vsh_bundle_state:
    action: "set_enabled"
    canonical_names: "{{ valet_canonical_names }}"
  when: valet_all_services | selectattr('type', 'equalto', 'service') | list | length > 0

- name: "internal-actions » handle | enable resolved services"
  ansible.builtin.systemd:
    name: "{{ service_item.service.name }}"
    state: started
    enabled: true
    scope: "{{ service_item.service.scope }}"
    daemon_reload: true
  become: "{{ service_item.service.scope == 'system' }}"
  loop: "{{ valet_all_services| selectattr('type', 'equalto', 'service') | list }}"
  loop_control:
    loop_var: service_item
  when: service_item.service.name is defined and service_item.enable_allowed

## end handle services states
########################

#######################
## start handle defaults

- name: "internal-actions » handle | include valet services file to check existing defaults"
  ansible.builtin.include_vars:
    file: "{{ valet_etc_services_file }}"
    name: valet_sh_services_obj

- name: "internal-actions » handle | filter bundles with multiple versions for default handling"
  ansible.builtin.set_fact:
    valet_all_services_for_defaults: "{{ valet_all_services_for_defaults | default([]) + [service_item] }}"
  loop: "{{ valet_all_services }}"
  loop_control:
    loop_var: service_item
  when:
    - valet_sh_bundle_definitions[service_item.type ~ 's'][service_item.name].versions | default([]) | length > 1

- name: "internal-actions » handle | set valet_all_services to defaultable bundles"
  ansible.builtin.set_fact:
    valet_all_services: "{{ valet_all_services_for_defaults | default([]) }}"

- name: "internal-actions » handle | run default action for bundles with multiple versions"
  ansible.builtin.include_tasks: "ubuntu/actions/default.yml"
  when: valet_all_services | length > 0

## end handle defaults
########################
