##
#   Copyright 2023 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "internal-actions » sub-handle-state | reset valet_service_name_alias variable"
  ansible.builtin.set_fact:
    valet_service_name_alias: ""

- name: "internal-actions » sub-handle-state | check for alias service name"
  ansible.builtin.set_fact:
    valet_service_name_alias: "{{ valet_sh_service_alias_mapping_item.value }}"
  when: valet_sh_service_alias_mapping_item.key == valet_current_service_item.key
  with_dict: "{{ valet_sh_service_alias_mapping }}"
  loop_control:
    loop_var: valet_sh_service_alias_mapping_item

- name: "internal-actions » sub-handle-state | enable {{ valet_current_service_item.key }} service"
  ansible.builtin.systemd:
    name: "{{ valet_current_service_item.key }}"
    enabled: true
    state: restarted
  become: true
  when: valet_service_name_alias|length == 0 and valet_current_service_item.value|bool

- name: "internal-actions » sub-handle-state | enable service '{{ valet_current_service_item.key }}' with alias '{{ valet_service_name_alias }}'"
  ansible.builtin.systemd:
    name: "{{ valet_service_name_alias }}"
    enabled: true
    state: restarted
  become: true
  when: valet_service_name_alias|length > 0 and valet_current_service_item.value|bool

- name: "internal-actions » sub-handle-state | disable {{ valet_current_service_item.key }} service"
  ansible.builtin.systemd:
    name: "{{ valet_current_service_item.key }}"
    enabled: false
    state: stopped
  become: true
  when: valet_service_name_alias|length == 0 and not valet_current_service_item.value|bool

- name: "internal-actions » sub-handle-state | disable service '{{ valet_current_service_item.key }}' with alias '{{ valet_service_name_alias }}'"
  ansible.builtin.systemd:
    name: "{{ valet_service_name_alias }}"
    enabled: false
    state: stopped
  become: true
  when: valet_service_name_alias|length > 0 and not valet_current_service_item.value|bool
