---

service:
  name:
    ubuntu: "vsh-rabbitmq312"
    mac: "vsh-rabbitmq312"
  scope:
    ubuntu: "user"
    mac: "user"
  provider:
    ubuntu: "systemd"
    mac: "container"

configuration:
  docker_image: "docker.io/rabbitmq:3.12-management"
  ports:
    http: 15673
    amqp: 5673
  base_path: "/usr/local/valet-sh/packages/rabbitmq312"
