---

service:
  name:
    ubuntu: "vsh-rabbitmq313"
    mac: "vsh-rabbitmq313"
  scope:
    ubuntu: "user"
    mac: "user"

configuration:
  docker_image: "docker.io/rabbitmq:3.13-management"
  ports:
    http: 15673
    amqp: 5673
