---

service:
  name:
    ubuntu: "vsh-rabbitmq313"
    mac: "vsh-rabbitmq313"
  scope:
    ubuntu: "user"
    mac: "user"
  provider:
    ubuntu: "systemd"
    mac: "container"

configuration:
  docker_image: "docker.io/rabbitmq:3.13-management"
  ports:
    http: 15674
    amqp: 5674
  base_path: "/usr/local/valet-sh/packages/rabbitmq313"
