---

service:
  name:
    ubuntu: "vsh-rabbitmq40"
    mac: "vsh-rabbitmq40"
  scope:
    ubuntu: "user"
    mac: "user"

configuration:
  docker_image: "docker.io/rabbitmq:4.0-management"
  ports:
    http: 15675
    amqp: 5675
  base_path: "/usr/local/valet-sh/packages/rabbitmq40"