---

service:
  name:
    ubuntu: "vsh-rabbitmq41"
    mac: "vsh-rabbitmq41"
  scope:
    ubuntu: "user"
    mac: "user"
  provider:
    ubuntu: "systemd"
    mac: "container"

configuration:
  docker_image: "docker.io/rabbitmq:4.1-management"
  ports:
    http: 15676
    amqp: 5676
  base_path: "/usr/local/valet-sh/packages/rabbitmq41"
