---

service:
  name:
    ubuntu: "vsh-rabbitmq43"
    mac: "vsh-rabbitmq43"
  scope:
    ubuntu: "user"
    mac: "user"
  provider:
    ubuntu: "systemd"
    mac: "container"

configuration:
  docker_image: "docker.io/rabbitmq:4.3-management"
  ports:
    http: 15678
    amqp: 5678
  base_path: "/usr/local/valet-sh/packages/rabbitmq43"
