---

service:
  name:
    ubuntu: "vsh-rabbitmq43"
    mac: "vsh-rabbitmq43"
  scope:
    ubuntu: "user"
    mac: "user"

configuration:
  docker_image: "docker.io/rabbitmq:4.3-management"
  ports:
    http: 15677
    amqp: 5677
