##
#   Copyright 2023 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "Include 'partials/load-valet-sh-file.yml'"
  ansible.builtin.include_tasks: "partials/load-valet-sh-file.yml"
  when: valet_sh_project_vars is not defined

- name: "Link | set 'link_name' when .valet-sh.yaml file was found"
  ansible.builtin.set_fact:
    link_name: "{{ valet_sh_project_vars.instance.key }}"
  when:
    - (link_name is not defined or link_name|length == 0)
    - valet_sh_project_vars is defined
    - valet_sh_project_vars.instance is defined
    - valet_sh_project_vars.instance.key is defined

- name: "Link | check if link_name variable is set"
  ansible.builtin.fail:
    msg: "link_name variable is not set"
  when: link_name is not defined or link_name|length == 0

- name: "Link | check if valet_current_path variable is set"
  ansible.builtin.fail:
    msg: "valet_current_path variable is not set"
  when: valet_current_path is not defined

- name: "Link | fail when name is blacklisted"
  ansible.builtin.fail:
    msg: "{{ link_name }} is not allowed!"
  when: "link_name in valet_link_blacklist"

- name: "Include 'sub/read.yml'"
  ansible.builtin.include_tasks: "sub/read.yml"

- name: "Block"
  when: "link_name in valet_links_obj.valet_links.links_index"
  block:
    - name: "Link | set empty array 'new_valet_links'"
      ansible.builtin.set_fact:
        new_valet_links: []

    - name: "Link | add existing links to 'new_valet_links' array"
      ansible.builtin.set_fact:
        new_valet_links: "{{ new_valet_links + [item] }}"
      when: "item.name != link_name"
      with_items: "{{ valet_links_obj.valet_links.links }}"

    - name: "Link | assemble new valet_links_object"
      ansible.builtin.set_fact:
        valet_links_obj:
          valet_links:
            links_index: "{{ valet_links_obj.valet_links.links_index | difference ([link_name]) }}"
            links: "{{ new_valet_links }}"

- name: "Link | change 'valet_current_path' when .valet-sh.yaml file was found"
  ansible.builtin.set_fact:
    valet_current_path: "{{ valet_current_path }}/{{ valet_sh_project_vars.instance.path }}"
  when:
    - valet_sh_project_vars is defined
    - valet_sh_project_vars.instance is defined
    - valet_sh_project_vars.instance.path is defined

- name: "Link | check selected php version"
  ansible.builtin.set_fact:
    current_php_version: "{{ php_version }}"
  when: (php_version is defined) and (php_version | length > 0)

- name: "Link | check for php version in .valet-sh.yml file"
  ansible.builtin.set_fact:
    current_php_version: "php{{ valet_sh_project_vars.services.php.version | replace('.', '') }}"
  when:
    - valet_sh_project_vars is defined
    - valet_sh_project_vars.services is defined
    - valet_sh_project_vars.services.php is defined
    - valet_sh_project_vars.services.php.version is defined
    - current_php_version is not defined

- name: "Block"
  block:
    - name: "Link | include valet services file"
      ansible.builtin.include_vars:
        file: "{{ valet_etc_services_file }}"
        name: valet_sh_services_obj
    - name: "Link | check for system default php version in services.yml file"
      ansible.builtin.set_fact:
        current_php_version: "{{ valet_sh_services_obj.defaults.php }}"
      when:
        - valet_sh_services_obj is defined
        - valet_sh_services_obj.defaults is defined
        - valet_sh_services_obj.defaults.php is defined
  when: current_php_version is not defined or current_php_version|length==0

- name: "Link | set default php version"
  ansible.builtin.set_fact:
    current_php_version: "{{ php_default_version_string }}"
  when: (current_php_version is undefined) or (current_php_version | length == 0)

- name: "Block"
  block:
    - name: "Link | check if php_version string mapped to origin"
      ansible.builtin.set_fact:
        current_php_version: "{{ valet_sh_available_php_versions_alias_mapping_item.0.origin }}"
      when: current_php_version in valet_sh_available_php_versions_alias_mapping_item.1
      with_subelements:
        - "{{ available_php_versions_alias_mapping }}"
        - aliases
      loop_control:
        loop_var: valet_sh_available_php_versions_alias_mapping_item
  when: "current_php_version not in available_php_versions"

- name: "Link | fail when php_version is unknown"
  ansible.builtin.fail:
    msg: "unknown php version '{{ current_php_version }}'"
  when: "current_php_version not in available_php_versions"

- name: "Link | generate ssl-certificate for {{ link_name }}"
  ansible.builtin.include_role:
    name: certificate
    public: true
  vars:
    cert_prefix: "{{ link_name }}"

- name: "Block"
  block:
    - name: Set fact for restart_php_service
      ansible.builtin.set_fact:
        restart_php_service: "{{ current_php_version[:3] }}{{ current_php_version[-2:] | join('.') }}-fpm"

    - name: "Actions » restart | restart {{ restart_php_service }} (running as root)"
      systemd:
        name: "{{ restart_php_service }}"
      become: true
      failed_when: false
      when: current_php_version in valet_sh_service_privileged_services

    - name: "Actions » restart | restart {{ restart_php_service }}"
      ansible.builtin.systemd:
        name: "{{ restart_php_service }}"
      failed_when: false
      when: current_php_version not in valet_sh_service_privileged_services
  when: current_php_version is defined

- name: "Link | find a matching application template"
  block:
    - name: "Include 'templates/magento2.yml'"
      ansible.builtin.include_tasks: templates/magento2.yml
    - name: "Include 'templates/neos.yml'"
      ansible.builtin.include_tasks: templates/neos.yml
    - name: "Include 'templates/typo3.yml'"
      ansible.builtin.include_tasks: templates/typo3.yml
    - name: "Include 'templates/shopware6.yml'"
      ansible.builtin.include_tasks: templates/shopware6.yml
    - name: "Include 'templates/magento1.yml'"
      ansible.builtin.include_tasks: templates/magento1.yml
    - name: "Include templates/fallback.yml"
      ansible.builtin.include_tasks: templates/fallback.yml
  when: not template_found

- name: "Link | create new valet_link variable"
  ansible.builtin.set_fact:
    new_valet_link:
      - name: "{{ link_name }}"
        path: "{{ valet_current_path }}"
        ssl: true
        phpVersion: "{{ current_php_version }}"
        template: "{{ nginx_template }}"

- name: "Link | assemble new valet_links_object"
  ansible.builtin.set_fact:
    valet_links_obj:
      valet_links:
        links_index: "{{ valet_links_obj.valet_links.links_index + [link_name] }}"
        links: "{{ valet_links_obj.valet_links.links + new_valet_link }}"

- name: "Include 'partials/update-default-vhost-template.yml'"
  ansible.builtin.include_tasks: "partials/update-default-vhost-template.yml"

- name: "Include 'sub/write.yml'"
  ansible.builtin.include_tasks: "sub/write.yml"
