##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "ensure rabbitmq is installed"
  ansible.builtin.shell: "/opt/homebrew/bin/brew install rabbitmq"

- name: "ensure rabbitmq is restarted"
  ansible.builtin.shell: "/opt/homebrew/bin/brew services restart rabbitmq"

- name: set 'cert_prefix' variable
  ansible.builtin.set_fact:
    cert_prefix: "rabbitmq"

- name: "generate ssl-certificate for rabbitmq.{{ development_tld }}"
  ansible.builtin.include_role:
    name: certificate
    public: true

- name: provide nginx vhost configuration for rabbitmq management plugin
  ansible.builtin.template:
    src: "rabbitmq.conf.j2"
    dest: "{{ valet_sh_prefix }}/etc/nginx/conf.d/rabbitmq.conf"
    mode: "0644"
  notify: brew | nginx | restarted

- name: unset 'cert_prefix' variable
  ansible.builtin.set_fact:
    cert_prefix: "{{ non_existent | default(None) }}"
