##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: ensure mysql wrapper script is up2date
  ansible.builtin.template:
    src: "wrappers/mysql/mysql-wrapper.j2"
    dest: "/usr/local/bin/mysql"
    mode: "0755"
  become: true

- name: ensure mysqladmin wrapper script is up2date
  ansible.builtin.template:
    src: "wrappers/mysql/mysqladmin-wrapper.j2"
    dest: "/usr/local/bin/mysqladmin"
    mode: "0755"
  become: true

- name: ensure mysqldump wrapper script is up2date
  ansible.builtin.template:
    src: "wrappers/mysql/mysqldump-wrapper.j2"
    dest: "/usr/local/bin/mysqldump"
    mode: "0755"
  become: true

- name: ensure mariadb wrapper script is up2date
  ansible.builtin.template:
    src: "wrappers/mysql/mysql-wrapper.j2"
    dest: "/usr/local/bin/mariadb"
    mode: "0755"
  become: true

- name: "create symlinks for default mysql"
  file:
    src: "/usr/local/bin/{{ current_mysql_default_linkname }}{{ item.version }}"
    dest: "/usr/local/bin/default-{{ current_mysql_default_linkname }}"
    state: link
    force: true
  become: true
  with_items:
    - mysql
    - mysqldump
    - mysqladmin
  loop_control:
    loop_var: current_mysql_default_linkname
  when: item.name == "mysql"

- name: "block for mariadb"
  when: item.name == "mariadb"
  block:
    - name: "create symlinks for default mysql"
      file:
        src: "/usr/local/bin/mariadb{{ item.version }}"
        dest: "/usr/local/bin/default-mysql"
        state: link
        force: true
      become: true

    - name: "create symlinks for default mysqladmin"
      file:
        src: "/usr/local/bin/mariaadmin{{ item.version }}"
        dest: "/usr/local/bin/default-mysqladmin"
        state: link
        force: true
      become: true

    - name: "create symlinks for default mysqldump"
      file:
        src: "/usr/local/bin/mariadump{{ item.version }}"
        dest: "/usr/local/bin/default-mysqldump"
        state: link
        force: true
      become: true

- name: "provide nginx stream configuration"
  template:
    src: "nginx/mysql.conf.j2"
    dest: "{{ valet_sh_prefix }}/etc/nginx/stream.d/mysql.conf"
    mode: "0644"
  notify: brew | nginx | restarted
