##
#   Copyright 2026 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: ensure rabbitmqctl wrapper script is up2date
  ansible.builtin.template:
    src: "wrappers/rabbitmq/rabbitmqctl-wrapper.j2"
    dest: "/usr/local/bin/rabbitmqctl"
    mode: "0755"
    owner: "{{ current_user }}"
    group: "{{ current_group }}"
  become: true

- name: "create symlinks for default rabbitmqctl"
  file:
    src: "/usr/local/bin/rabbitmqctl{{ item.version }}"
    dest: "/usr/local/bin/default-rabbitmqctl"
    owner: "{{ current_user }}"
    group: "{{ current_group }}"
    state: link
    force: true
  become: true

- name: "provide nginx stream configuration"
  template:
    src: "nginx/rabbitmq.conf.j2"
    dest: "{{ valet_sh_prefix }}/etc/nginx/stream.d/rabbitmq.conf"
    owner: "{{ current_user }}"
    group: "{{ current_group }}"
    mode: "0644"
  notify: brew | nginx | restarted
