##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: set max_map_count to 262144
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: "262144"
    state: present
    reload: false
  become: true

- name: set fs.inotify.max_user_watches to 1048576
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: "1048576"
    state: present
    reload: false
  become: true

- name: "ensure brew_x86 wrapper script is removed (on apple silicon)"
  file:
    path: /usr/local/bin/brew_x86
    state: absent

- name: ensure homebrew is installed
  ansible.builtin.shell: '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"'
  args:
    creates: "/opt/homebrew/bin/brew"

- name: Ensure valet-sh/php is tapped
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} tap valet-sh/php"
  environment:
    NONINTERACTIVE: true

- name: Ensure valet-sh/php is trusted
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} trust valet-sh/php"

- name: ensure LaunchDaemons script for maxfiles limit is deployed
  ansible.builtin.template:
    src: "limit.maxfiles.conf.j2"
    dest: "/Library/LaunchDaemons/limit.maxfiles.plist"
  become: true

- name: ensure maxfile limit daemon is started
  ansible.builtin.shell: "launchctl load -w /Library/LaunchDaemons/limit.maxfiles.plist"

- name: ensure service tap is installed
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services list"

- name: "ensure '{{ current_home }}/.config/container' exists"
  ansible.builtin.file:
    path: "{{ current_home }}/.config/container"
    state: directory
    mode: "0755"

- name: "ensure '{{ current_home }}/.config/container/config.toml' is up2date"
  ansible.builtin.copy:
    content: |
      [dns]
      domain = "vsh-services"
    dest: "{{ current_home }}/.config/container/config.toml"
    mode: "0644"

- name: check if '/usr/local/bin/container' exists
  ansible.builtin.stat:
    path: "/usr/local/bin/container"
  register: container_install_state_obj

- name: install apple container when absent
  when: not container_install_state_obj.stat.exists|bool
  block:
    - name: Download apple container installer
      ansible.builtin.get_url:
        url: "https://github.com/apple/container/releases/download/1.0.0/container-1.0.0-installer-signed.pkg"
        dest: "/tmp/apple-container.pkg"
        mode: "0755"
        force: true

    - name: Install apple container
      ansible.builtin.command:
        cmd: "installer -pkg /tmp/apple-container.pkg -target /"
      become: true

    - name: ensure apple container is started
      shell: container system start --enable-kernel-install

- name: "ensure '{{ current_home }}/Library/LaunchAgents' exists"
  ansible.builtin.file:
    path: "{{ current_home }}/Library/LaunchAgents"
    state: directory
    mode: "0755"

- name: "ensure '/usr/local/valet-sh/bin/' exists"
  ansible.builtin.file:
    path: "/usr/local/valet-sh/bin/"
    state: directory
    mode: "0755"

- name: "ensure LaunchAgent '{{ current_home }}/Library/LaunchAgents/com.apple.container.autostart.plist' is up2date"
  ansible.builtin.template:
    src: "LaunchAgent/com.apple.container.autostart.plist.j2"
    dest: "{{ current_home }}/Library/LaunchAgents/com.apple.container.autostart.plist"

- name: "ensure LaunchAgent '{{ current_home }}/Library/LaunchAgents/sh.valet.container.autostart.plist' is up2date"
  ansible.builtin.template:
    src: "LaunchAgent/sh.valet.container.autostart.plist.j2"
    dest: "{{ current_home }}/Library/LaunchAgents/sh.valet.container.autostart.plist"

- name: "ensure '/usr/local/valet-sh/etc/bin/container-autostart.sh' is up2date"
  ansible.builtin.template:
    src: "container-autostart.sh.j2"
    dest: "/usr/local/valet-sh/bin/container-autostart.sh"
    mode: "0755"

- name: "ensure '/usr/local/valet-sh/etc/container-autostart' exists"
  ansible.builtin.file:
    path: "/usr/local/valet-sh/etc/container-autostart"
    state: touch

- name: "ensure '{{ current_home }}/Library/LaunchAgents' exists"
  ansible.builtin.file:
    path: "{{ current_home }}/Library/LaunchAgents"
    state: directory
    mode: "0755"

- name: ensure apple container is started
  ansible.builtin.shell: "launchctl load -w {{ current_home }}/Library/LaunchAgents/com.apple.container.autostart.plist"

- name: ensure apple container is started
  ansible.builtin.shell: "launchctl load -w {{ current_home }}/Library/LaunchAgents/sh.valet.container.autostart.plist"

- name: Mark common as installed
  vsh_bundle_state:
    action: "installed"
    name: "common"
