##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "ensure brew_x86 wrapper script is removed (on apple silicon)"
  file:
    path: /usr/local/bin/brew_x86
    state: absent

- name: Ensure valet-sh/php is untapped
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} untap valet-sh/php"

- name: "ensure Service '/Library/LaunchDaemons/limit.maxfiles.plist' is unloaded"
  ansible.builtin.shell: "launchctl unload /Library/LaunchDaemons/limit.maxfiles.plist"

- name: ensure '/Library/LaunchDaemons/limit.maxfiles.plist' is absent
  ansible.builtin.file:
    path: "/Library/LaunchDaemons/limit.maxfiles.plist"
    state: absent
  become: true

- name: "unload LaunchAgent '{{ current_home}}/Library/LaunchAgents/com.apple.container.autostart.plist'"
  ansible.builtin.shell: "launchctl unload {{ current_home }}/Library/LaunchAgents/com.apple.container.autostart.plist"

- name: "ensure LaunchAgent '{{ current_home}}/Library/LaunchAgents/com.apple.container.autostart.plist' is absent"
  ansible.builtin.file:
    path: "{{ current_home }}/Library/LaunchAgents/com.apple.container.autostart.plist"
    state: absent

- name: "unload LaunchAgent '{{ current_home}}/Library/LaunchAgents/sh.valet.container.autostart.plist'"
  ansible.builtin.shell: "launchctl unload {{ current_home }}/Library/LaunchAgents/sh.valet.container.autostart.plist"

- name: "ensure LaunchAgent '{{ current_home}}/Library/LaunchAgents/sh.valet.container.autostart.plist' is absent"
  ansible.builtin.file:
    path: "{{ current_home }}/Library/LaunchAgents/sh.valet.container.autostart.plist"
    state: absent

- name: "ensure apple container is removed - data retained"
  ansible.builtin.shell: "/usr/local/bin/uninstall-container.sh -k"
  when: "'--purge' not in valet_cli_opts"

- name: "ensure apple container is removed - data removed"
  ansible.builtin.shell: "/usr/local/bin/uninstall-container.sh -d"
  when: "'--purge' in valet_cli_opts"

- name: "remove apple container uninstall script"
  ansible.builtin.file:
    path: "/usr/local/bin/uninstall-container.sh"
    state: absent

- name: Mark common as uninstalled
  vsh_bundle_state:
    action: "uninstalled"
    name: "common"
