---

service:
  name:
    ubuntu: "vsh-redis-server"
    mac: "vsh-redis"
  scope:
    ubuntu: "user"
    mac: "user"

configuration:
  docker_image: "docker.io/redis/redis:latest"
  ports:
    redis: 6379
