#!/bin/bash

AVAILABLE_PHP_VERSION='5.6 7.0 7.1 7.2 7.3 7.4 8.0 8.1'

function get_target_version {
    VALET_SH_FILE=$1

    SELECTED_PHP_VERSION=$(/usr/local/valet-sh/venv/bin/shyaml get-value services.php.version < "${VALET_SH_FILE}" 2>/dev/null)
   	# shellcheck disable=SC2181
    if [ $? -eq 0 ]
    then
      if [[ " $AVAILABLE_PHP_VERSION " =~ .*\ $SELECTED_PHP_VERSION\ .* ]]; then
         TARGET_PHP_VERSION=$SELECTED_PHP_VERSION
         return 0
      fi
    fi
    return 1
}

function search_for_valet_sh_yml () {
  local slashes=${PWD//[^\/]/}
  local directory="$PWD"
  for (( n=${#slashes}; n>0; --n ))
  do
    test -f "$directory/.valet-sh.yml" && echo "$directory/.valet-sh.yml" && return
    directory="$directory/.."
  done
  return
}

CURRENT_VALET_SH_FILE=$(search_for_valet_sh_yml)

if [[ $CURRENT_VALET_SH_FILE ]]
then
  get_target_version $CURRENT_VALET_SH_FILE
  # shellcheck disable=SC2181
  if [ $? -eq 0 ]
  then
    /usr/bin/php"${TARGET_PHP_VERSION}" "$@"
  else
    /usr/bin/php "$@"
  fi
else
  /usr/bin/php "$@"
fi