##
#   Copyright 2022 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---
- block:
    - name: "workflows » magento2 » services » elasticsearch | check if elasticsearch{{ valet_sh_project_vars.services.elasticsearch.version  }} is installed"
      vsh_bundle_state:
        action: "is_installed"
        canonical_names: "elasticsearch{{ valet_sh_project_vars.services.elasticsearch.version }}"
      register: elasticsearch_installed

    - name: "workflows » magento2 » services » elasticsearch | resolve elasticsearch{{ valet_sh_project_vars.services.elasticsearch.version }} service"
      vsh_bundle_resolver:
        service: "elasticsearch{{ valet_sh_project_vars.services.elasticsearch.version }}"
        current_os: "{{ current_os }}"
      register: elasticsearch_install

# TODO if empty/not defined plugin list dont run the plugin installation

    - name: "workflows » magento2 » check-vars | read elasticsearch plugins from .valet-sh.yml"
      ansible.builtin.set_fact:
        elasticsearch_plugins: "{{ valet_sh_project_vars.services.elasticsearch.plugins }}"

    - name: "workflows » magento2 » services » elasticsearch | include service-specific roles"
      ansible.builtin.include_role:
        name: "elasticsearch"
      vars:
        valet_resolved_service: "{{ elasticsearch_install }}"
        valet_install_services: ["elasticsearch{{ valet_sh_project_vars.services.elasticsearch.version }}"]
      when: not elasticsearch_installed.is_installed

    - name: "workflows » magento2 » services » elasticsearch | include valet-service role to set defaults"
      ansible.builtin.include_role:
        name: "valet-service"
      vars:
        valet_sh_service_internal_action: true
        valet_service_action: "handle"
        valet_sh_newly_installed_services: "{{ elasticsearch_install }}"

    - name: "workflows » magento2 » services » elasticsearch | ensure elasticsearch{{ valet_sh_project_vars.services.elasticsearch.version }} is started and enabled"
      ansible.builtin.systemd:
        name: "vsh-elasticsearch{{ valet_sh_project_vars.services.elasticsearch.version }}"
        state: started
        enabled: true
        scope: user

    - name: "workflows » magento2 » services » elasticsearch | set elasticsearch{{ valet_sh_project_vars.services.elasticsearch.version }} as default"
      vsh_bundle_state:
        action: "set_default"
        name: "elasticsearch"
        canonical_names: "elasticsearch{{ valet_sh_project_vars.services.elasticsearch.version }}"

    - name: "workflows » magento2 » services » elasticsearch | set elasticsearch{{ valet_sh_project_vars.services.elasticsearch.version }} as enabled"
      vsh_bundle_state:
        action: "set_enabled"
        canonical_names: "elasticsearch{{ valet_sh_project_vars.services.elasticsearch.version }}"

    - name: "workflows » magento2 » services » elasticsearch | wait for elasticsearch to be reachable"
      ansible.builtin.wait_for:
        port: "{{ valet_sh_elasticsearch_ports[valet_sh_project_vars.services.elasticsearch.version] }}"
        delay: 5

    - name: "workflows » magento2 » services » elasticsearch | check if plugins are already installed"
      containers.podman.podman_container_exec:
        name: "vsh-elasticsearch{{ valet_sh_project_vars.services.elasticsearch.version }}"
        command: "bin/elasticsearch-plugin list"
      register: installed_plugins

    - name: "workflows » magento2 » services » elasticsearch | install plugins defined in .valet-sh.yml"
      containers.podman.podman_container_exec:
        name: "vsh-elasticsearch{{ valet_sh_project_vars.services.elasticsearch.version }}"
        command: "{{ elasticsearch_install.services[0].configuration.plugins.install_command | replace('{{ name }}', current_elasticsearch_plugin) }}"
      with_items: "{{ elasticsearch_plugins }}"
      loop_control:
        loop_var: current_elasticsearch_plugin
      when: current_elasticsearch_plugin not in installed_plugins.stdout

    - name: "workflows » magento2 » services » elasticsearch | ensure elasticsearch{{ valet_sh_project_vars.services.elasticsearch.version }} is restarted after plugin installation"
      ansible.builtin.systemd:
        name: "vsh-elasticsearch{{ valet_sh_project_vars.services.elasticsearch.version }}"
        state: restarted
        scope: user
  when:
    - current_os == "ubuntu"
    - valet_sh_project_vars.services is defined
    - valet_sh_project_vars.services.elasticsearch is defined
    - valet_sh_project_vars.services.elasticsearch.version is defined

- block:
    - name: "workflows » magento2 » services » opensearch | check if opensearch{{ valet_sh_project_vars.services.opensearch.version }} is installed"
      vsh_bundle_state:
        action: "is_installed"
        canonical_names: "opensearch{{ valet_sh_project_vars.services.opensearch.version }}"
      register: opensearch_installed

    - name: "workflows » magento2 » services » opensearch | resolve opensearch{{ valet_sh_project_vars.services.opensearch.version }} service"
      vsh_bundle_resolver:
        name: "opensearch{{ valet_sh_project_vars.services.opensearch.version }}"
        current_os: "{{ current_os }}"
      register: opensearch_install

    - name: "workflows » magento2 » check-vars | read opensearch plugins from .valet-sh.yml"
      ansible.builtin.set_fact:
        opensearch_plugins: "{{ valet_sh_project_vars.services.opensearch.plugins }}"

    - name: "include service-specific roles"
      ansible.builtin.include_role:
        name: "opensearch"
      vars:
        valet_resolved_service: "{{ opensearch_install }}"
        valet_install_services: ["opensearch{{ valet_sh_project_vars.services.opensearch.version }}"]
      when: not opensearch_installed.is_installed

    - name: "workflows » magento2 » services » opensearch | include valet-service role to set defaults"
      ansible.builtin.include_role:
        name: "valet-service"
      vars:
        valet_sh_service_internal_action: true
        valet_service_action: "handle"
        valet_sh_newly_installed_services: "{{ opensearch_install }}"

    - name: "workflows » magento2 » services » opensearch | ensure opensearch{{ valet_sh_project_vars.services.opensearch.version }} is started and enabled"
      ansible.builtin.systemd:
        name: "vsh-opensearch{{ valet_sh_project_vars.services.opensearch.version }}"
        state: started
        enabled: true
        scope: user

    - name: "workflows » magento2 » services » opensearch | set opensearch{{ valet_sh_project_vars.services.opensearch.version }} as default"
      vsh_bundle_state:
        action: "set_default"
        name: "opensearch"
        canonical_names: "opensearch{{ valet_sh_project_vars.services.opensearch.version }}"

    - name: "workflows » magento2 » services » opensearch | set opensearch{{ valet_sh_project_vars.services.opensearch.version }} as enabled"
      vsh_bundle_state:
        action: "set_enabled"
        canonical_names: "opensearch{{ valet_sh_project_vars.services.opensearch.version }}"

    - name: "workflows » magento2 » services » opensearch | wait for opensearch to be reachable"
      ansible.builtin.wait_for:
        port: "{{ valet_sh_opensearch_ports[valet_sh_project_vars.services.opensearch.version] }}"
        delay: 5

    - name: "workflows » magento2 » services » opensearch | check if plugins are already installed"
      containers.podman.podman_container_exec:
        name: "vsh-opensearch{{ valet_sh_project_vars.services.opensearch.version }}"
        command: "bin/opensearch-plugin list"
      register: installed_plugins

    - name: "workflows » magento2 » services » opensearch | install plugins defined in .valet-sh.yml"
      containers.podman.podman_container_exec:
        name: "vsh-opensearch{{ valet_sh_project_vars.services.opensearch.version }}"
        command: "{{ opensearch_install.services[0].configuration.plugins.install_command | replace('{{ name }}', current_opensearch_plugin) }}"
      with_items: "{{ opensearch_plugins }}"
      loop_control:
        loop_var: current_opensearch_plugin
      when: current_opensearch_plugin not in installed_plugins.stdout

    - name: "workflows » magento2 » services » opensearch | ensure opensearch{{ valet_sh_project_vars.services.opensearch.version }} is restarted after plugin installation"
      ansible.builtin.systemd:
        name: "vsh-opensearch{{ valet_sh_project_vars.services.opensearch.version }}"
        state: restarted
        scope: user
  when:
    - current_os == "ubuntu"
    - valet_sh_project_vars.services is defined
    - valet_sh_project_vars.services.opensearch is defined
    - valet_sh_project_vars.services.opensearch.version is defined

- block:
    - name: "workflows » magento2 » services » elasticsearch | ensure elasticsearch{{ valet_sh_project_vars.services.elasticsearch.version }} is started"
      ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services start vsh-elasticsearch{{ valet_sh_project_vars.services.elasticsearch.version }}"
    - name: "workflows » magento2 » services » elasticsearch | include valet services file"
      ansible.builtin.include_vars:
        file: "{{ valet_etc_services_file }}"
        name: valet_sh_services_obj

    - name: "workflows » magento2 » services » elasticsearch | prepare new config element"
      ansible.builtin.set_fact:
        new_service_state_element: "{ 'elasticsearch{{ valet_sh_project_vars.services.elasticsearch.version }}': true }"

    - name: "workflows » magento2 » services » elasticsearch | update service object"
      ansible.builtin.set_fact:
        valet_sh_services_updated_states: "{{ valet_sh_services_obj.states | combine(new_service_state_element) }}"

    - name: "workflows » magento2 » services » elasticsearch | merge objects"
      ansible.builtin.set_fact:
        valet_sh_services_obj:
          states: "{{ valet_sh_services_updated_states }}"
          defaults: "{{ valet_sh_services_obj.defaults }}"

    - name: "workflows » magento2 » services » elasticsearch | transform object into nice yaml output"
      ansible.builtin.set_fact:
        valet_etc_services_list: "{{ valet_sh_services_obj | to_nice_yaml(width=50, explicit_start=True, explicit_end=True) }}"

    - name: "workflows » magento2 » services » elasticsearch | write new services.yml file"
      ansible.builtin.copy:
        content: "{{ valet_etc_services_list }}"
        dest: "{{ valet_etc_services_file }}"

    - name: "workflows » magento2 » services » elasticsearch | wait for elasticsearch to be reachable"
      ansible.builtin.wait_for:
        port: "{{ valet_sh_elasticsearch_ports[valet_sh_project_vars.services.elasticsearch.version] }}"
        delay: 5
  when:
    - current_os == "mac"
    - valet_sh_project_vars.services is defined
    - valet_sh_project_vars.services.elasticsearch is defined
    - valet_sh_project_vars.services.elasticsearch.version is defined

- block:
    - name: "workflows » magento2 » services » opensearch | ensure opensearch{{ valet_sh_project_vars.services.opensearch.version }} is started"
      ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services start vsh-opensearch{{ valet_sh_project_vars.services.opensearch.version }}"

    - name: "workflows » magento2 » services » opensearch | include valet services file"
      ansible.builtin.include_vars:
        file: "{{ valet_etc_services_file }}"
        name: valet_sh_services_obj

    - name: "workflows » magento2 » services » opensearch | prepare new config element"
      ansible.builtin.set_fact:
        new_service_state_element: "{ 'opensearch{{ valet_sh_project_vars.services.opensearch.version }}': true }"

    - name: "workflows » magento2 » services » opensearch | update service object"
      ansible.builtin.set_fact:
        valet_sh_services_updated_states: "{{ valet_sh_services_obj.states | combine(new_service_state_element) }}"

    - name: "workflows » magento2 » services » opensearch | merge objects"
      ansible.builtin.set_fact:
        valet_sh_services_obj:
          states: "{{ valet_sh_services_updated_states }}"
          defaults: "{{ valet_sh_services_obj.defaults }}"

    - name: "workflows » magento2 » services » opensearch | transform object into nice yaml output"
      ansible.builtin.set_fact:
        valet_etc_services_list: "{{ valet_sh_services_obj | to_nice_yaml(width=50, explicit_start=True, explicit_end=True) }}"

    - name: "workflows » magento2 » services » opensearch | write new services.yml file"
      ansible.builtin.copy:
        content: "{{ valet_etc_services_list }}"
        dest: "{{ valet_etc_services_file }}"

    - name: "workflows » magento2 » services » opensearch | wait for opensearch to be reachable"
      ansible.builtin.wait_for:
        port: "{{ valet_sh_opensearch_ports[valet_sh_project_vars.services.opensearch.version] }}"
        delay: 5
  when:
    - current_os == "mac"
    - valet_sh_project_vars.services is defined
    - valet_sh_project_vars.services.opensearch is defined
    - valet_sh_project_vars.services.opensearch.version is defined
