##
#   Copyright 2021 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "workflows » magento2 » services | detect database"
  ansible.builtin.set_fact:
    database: "{{ item.key }}"
    database_version: "{{ item.value.version | replace('.', '') }}"
    database_config: "{{ item.value }}"
    database_canonical_name: "{{ item.key }}{{ item.value.version | replace('.', '') }}"
  with_dict: "{{ valet_sh_project_vars.services | default({}) }}"
  when: item.key in ['mysql', 'mariadb']

- block:
    - name: "workflows » magento2 » services » database | check if {{ database_canonical_name }} is installed"
      vsh_bundle_install_state_info:
        state: "present"
        name: "{{ database_canonical_name }}"
      register: database_installed

    - name: "workflows » magento2 » services » database | resolve {{ database_canonical_name }} service"
      vsh_bundle_resolver:
        name: "{{ database_canonical_name }}"
        current_os: "{{ current_os }}"
      register: database_install

    - name: "workflows » magento2 » services » database | include service-specific roles"
      ansible.builtin.include_role:
        name: "{{ if database == 'mysql' }}mysql-community-server{{ else }}mariadb-server{{ endif }}"
      vars:
        valet_resolved_service: "{{ database_install }}"
        valet_install_services: ["{{ database_canonical_name }}"]
      when: database_installed.kinds | length == 0

    - name: "workflows » magento2 » services » database | ensure {{ database_canonical_name }} is started"
      ansible.builtin.systemd:
        name: "vsh-{{ database_canonical_name }}"
        state: started
        enabled: true
        scope: user

    - name: "workflows » magento2 » services » database | set {{ database_canonical_name }} as default"
      vsh_bundle_state:
        action: "default"
        name: "{{ database }}"
        canonical_names: "{{ database_canonical_name }}"

    - name: "workflows » magento2 » services » database | set {{ database_canonical_name }} as enabled"
      vsh_bundle_state:
        action: "enabled"
        canonical_names: "{{ database_canonical_name }}"

    - name: "workflows » magento2 » services » database | wait for {{ database_canonical_name }} to be reachable"
      ansible.builtin.wait_for:
        port: "{{ database_install.services[0].configuration.ports.tcp }}"
        delay: 5
  when:
    - current_os == "ubuntu"
    - database is defined
    - database_version is defined

- block:
    - name: "workflows » magento2 » services » database | check if {{ database_canonical_name }} is installed"
      vsh_bundle_install_state_info:
        state: "present"
        name: "{{ database_canonical_name }}"
      register: database_installed

    - name: "workflows » magento2 » services » database | resolve {{ database_canonical_name }} service"
      vsh_bundle_resolver:
        name: "{{ database_canonical_name }}"
        current_os: "{{ current_os }}"
      register: database_install

    - name: "workflows » magento2 » services » database | include service-specific roles"
      ansible.builtin.include_role:
        name: "{{ if database == 'mysql' }}mysql-community-server{{ else }}mariadb-server{{ endif }}"
      vars:
        valet_resolved_service: "{{ database_install }}"
        valet_install_services: ["{{ database_canonical_name }}"]
      when: database_installed.kinds | length == 0

    - name: "workflows » magento2 » services » database | ensure {{ database_canonical_name }} is started"
      apple_container:
        name: "vsh-{{ database_canonical_name }}"
        state: started

    - name: "workflows » magento2 » services » database | set {{ database_canonical_name }} as default"
      vsh_bundle_state:
        action: "default"
        name: "{{ database }}"
        canonical_names: "{{ database_canonical_name }}"

    - name: "workflows » magento2 » services » database | set {{ database_canonical_name }} as enabled"
      vsh_bundle_state:
        action: "enabled"
        canonical_names: "{{ database_canonical_name }}"

    - name: "workflows » magento2 » services » database | wait for {{ database_canonical_name }} to be reachable"
      ansible.builtin.wait_for:
        host: "vsh-{{ database_canonical_name }}"
        port: "{{ database_install.services[0].configuration.ports.tcp }}"
        delay: 5
  when:
    - current_os == "mac"
    - database is defined
    - database_version is defined
