##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "workflows » magento2 » services | detect cache"
  ansible.builtin.set_fact:
    cache: "{{ item.key }}"
    cache_version: "{{ item.value.version | replace('.', '') }}"
    cache_config: "{{ item.value }}"
    cache_canonical_name: "{{ item.key }}{{ item.value.version | replace('.', '') }}"
  with_dict: "{{ valet_sh_project_vars.services | default({}) }}"
  when: item.key in ['redis', 'valkey']

- name: "workflows » magento2 » services | set default cache to redis if no cache is defined"
  ansible.builtin.set_fact:
    cache: "redis"
    cache_version: "{{ valet_sh_bundle_definitions.services.redis.default_version | replace('.', '') }}"
    cache_canonical_name: "redis{{ valet_sh_bundle_definitions.services.redis.default_version | replace('.', '') }}"
  when: cache is not defined

- block:
    - name: "workflows » magento2 » services » cache | check if {{ cache_canonical_name }} is installed"
      vsh_bundle_install_state_info:
        state: "present"
        name: "{{ cache_canonical_name }}"
      register: cache_installed

    - name: "workflows » magento2 » services » cache | resolve {{ cache_canonical_name }} service"
      vsh_bundle_resolver:
        name: "{{ cache_canonical_name }}"
        current_os: "{{ current_os }}"
      register: cache_install

    - name: "include service-specific roles"
      ansible.builtin.include_role:
        name: "{{ cache }}"
      vars:
        valet_resolved_service: "{{ cache_install }}"
        valet_install_services: ["{{ cache_canonical_name }}"]
      when: cache_installed.kinds | length == 0

    - name: "workflows » magento2 » services » cache | ensure {{ cache_canonical_name }} is started"
      ansible.builtin.systemd:
        name: vsh-{{ cache_canonical_name }}
        state: restarted
        enabled: true
        scope: user

    - name: "workflows » magento2 » services » cache | set {{ cache_canonical_name }} as enabled"
      vsh_bundle_state:
        action: "enabled"
        canonical_names: "{{ cache_canonical_name }}"

    - name: "workflows » magento2 » services » cache | wait for {{ cache_canonical_name }} to be reachable"
      ansible.builtin.wait_for:
        port: "{{ cache_install.services[0].configuration.ports.tcp }}"
        delay: 5
  when:
    - current_os == "ubuntu"

- block:
    - name: "workflows » magento2 » services » cache | check if {{ cache_canonical_name }} is installed"
      vsh_bundle_install_state_info:
        state: "present"
        name: "{{ cache_canonical_name }}"
      register: cache_installed

    - name: "workflows » magento2 » services » cache | resolve {{ cache_canonical_name }} service"
      vsh_bundle_resolver:
        name: "{{ cache_canonical_name }}"
        current_os: "{{ current_os }}"
      register: cache_install

    - name: "include service-specific roles"
      ansible.builtin.include_role:
        name: "{{ cache }}"
      vars:
        valet_resolved_service: "{{ cache_install }}"
        valet_install_services: ["{{ cache_canonical_name }}"]
      when: cache_installed.kinds | length == 0

    - name: "workflows » magento2 » services » cache | ensure {{ cache_canonical_name }} is started"
      apple_container:
        name: "vsh-{{ cache_canonical_name }}"
        state: started

    - name: "workflows » magento2 » services » cache | set {{ cache_canonical_name }} as enabled"
      vsh_bundle_state:
        action: "enabled"
        canonical_names: "{{ cache_canonical_name }}"

    - name: "workflows » magento2 » services » cache | wait for {{ cache_canonical_name }} to be reachable"
      ansible.builtin.wait_for:
        host: "vsh-{{ cache_canonical_name }}"
        port: "{{ cache_install.services[0].configuration.ports.tcp }}"
        delay: 5
  when:
    - current_os == "mac"
