##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "set handler_current_service fact"
  ansible.builtin.set_fact:
    handler_current_service: "{{ current_service }}"

- name: Ensure mailpit image is up2date
  apple_image:
    name: "{{ current_service.configuration.docker_image }}"
    pull: true
    state: present

- name: set 'cert_prefix' variable
  ansible.builtin.set_fact:
    cert_prefix: "mailpit"

- name: "generate ssl-certificate for {{ cert_prefix }}"
  ansible.builtin.include_role:
    name: certificate
    public: true

- name: provide nginx vhost for mailpit
  ansible.builtin.template:
    src: "mailpit.conf.j2"
    dest: "/opt/homebrew/etc/nginx/conf.d/mailpit.conf"
    mode: "0644"
  notify: brew | nginx | restarted

- name: unset 'cert_prefix' variable
  ansible.builtin.set_fact:
    cert_prefix: "{{ non_existent | default(None) }}"

- name: "ensure container 'vsh-{{ current_service.canonical }}' is started"
  apple_container:
    name: "vsh-{{ current_service.canonical }}"
    image: "{{ current_service.configuration.docker_image }}"
    cpus: "{{ current_service.configuration.limits.cpus | default(2) }}"
    memory: "{{ current_service.configuration.limits.memory | default('2g') }}"
    arch: "{{ current_service.configuration.arch | default(omit) }}"
    state: started
    env:
      - "MP_UI_BIND_ADDR=0.0.0.0:{{ current_service.configuration.ports.http }}"
      - "MP_SMTP_BIND_ADDR=0.0.0.0:{{ current_service.configuration.ports.smtp }}"

- name: Set container autostart
  ansible.builtin.lineinfile:
    path: /usr/local/valet-sh/etc/container-autostart
    line: "vsh-{{ current_service.canonical }}"
    state: "present"

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers

- name: "Add mailpit to installed services"
  vsh_bundle_state:
    action: "installed"
    canonical_names: "{{ current_service.canonical }}"

- name: "Mark mailpit as enabled in the services file"
  vsh_bundle_state:
    action: "enabled"
    canonical_names: "mailpit"
