##
#   Copyright 2023 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: Systemd | opensearch1 | started
  ansible.builtin.systemd:
    daemon_reload: true
    name: opensearch1
    state: started
  become: true

- name: Systemd | opensearch1 | stopped
  ansible.builtin.systemd:
    daemon_reload: true
    name: opensearch1
    state: stopped
  become: true

- name: Systemd | opensearch1 | restarted
  ansible.builtin.systemd:
    daemon_reload: true
    name: opensearch1
    state: restarted
  become: true

- name: Systemd | opensearch1 | reloaded
  ansible.builtin.systemd:
    daemon_reload: true
    name: opensearch1
    state: restarted
  become: true

- name: Brew | vsh-opensearch1 | restarted
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services restart vsh-opensearch1"

- name: Systemd | opensearch2 | started
  ansible.builtin.systemd:
    daemon_reload: true
    name: opensearch2
    state: started
  become: true

- name: Systemd | opensearch2 | stopped
  ansible.builtin.systemd:
    daemon_reload: true
    name: opensearch2
    state: stopped
  become: true

- name: Systemd | opensearch2 | restarted
  ansible.builtin.systemd:
    daemon_reload: true
    name: opensearch2
    state: restarted
  become: true

- name: Systemd | opensearch2 | reloaded
  ansible.builtin.systemd:
    daemon_reload: true
    name: opensearch2
    state: restarted
  become: true

- name: Brew | vsh-opensearch2 | restarted
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services restart vsh-opensearch2"
