##
#   Copyright 2023 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---
- name: systemd | vsh-opensearch1 | started
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ current_opensearch_systemd_name }}"
    state: started
    scope: "{{ current_opensearch_systemd_scope }}"

- name: systemd | vsh-opensearch1 | stopped
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ current_opensearch_systemd_name }}"
    state: stopped
    scope: "{{ current_opensearch_systemd_scope }}"

- name: systemd | vsh-opensearch1 | restarted
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ current_opensearch_systemd_name }}"
    state: restarted
    scope: "{{ current_opensearch_systemd_scope }}"

- name: systemd | vsh-opensearch1 | reloaded
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ current_opensearch_systemd_name }}"
    state: restarted
    scope: "{{ current_opensearch_systemd_scope }}"

- name: brew | vsh-opensearch1 | restarted
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services restart vsh-opensearch1"

- name: systemd | vsh-opensearch2 | started
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ current_opensearch_systemd_name }}"
    state: started
    scope: "{{ current_opensearch_systemd_scope }}"

- name: systemd | vsh-opensearch2 | stopped
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ current_opensearch_systemd_name }}"
    state: stopped
    scope: "{{ current_opensearch_systemd_scope }}"

- name: systemd | vsh-opensearch2 | restarted
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ current_opensearch_systemd_name }}"
    state: restarted
    scope: "{{ current_opensearch_systemd_scope }}"

- name: systemd | vsh-opensearch2 | reloaded
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ current_opensearch_systemd_name }}"
    state: restarted
    scope: "{{ current_opensearch_systemd_scope }}"

- name: brew | vsh-opensearch2 | restarted
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services restart vsh-opensearch2"
