##
#   Copyright 2021 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: debug current_mariadb_service
  ansible.builtin.debug:
    var: current_mariadb_service

- name: "create mariadb base directories"
  ansible.builtin.file:
    path: "{{ current_mariadb_base_directory }}"
    owner: "valet"
    group: "valet"
    mode: "0755"
    state: directory
  become: true
  with_items:
    - "{{ current_mariadb_service.configuration.base_path }}"
    - "{{ current_mariadb_service.configuration.base_path }}/user"
    - "{{ current_mariadb_service.configuration.base_path }}/etc"
    - "{{ current_mariadb_service.configuration.base_path }}/etc/conf.d"
  loop_control:
    loop_var: current_mariadb_base_directory

- name: "Pull vsh-{{ current_mariadb_service.canonical }} image"
  containers.podman.podman_image:
    name: "{{ current_mariadb_service.configuration.docker_image }}"
    pull: true
    state: present

- name: "provide .my.cnf configuration file"
  ansible.builtin.template:
    src: "ubuntu/{{ current_mariadb_service.canonical }}/.my.cnf.j2"
    dest: "{{ current_mariadb_service.configuration.base_path }}/user/.my.cnf"
    mode: "0644"

- name: "provide my.cnf configuration file"
  ansible.builtin.template:
    src: "ubuntu/{{ current_mariadb_service.canonical }}/my.cnf.j2"
    dest: "{{ current_mariadb_service.configuration.base_path }}/etc/my.cnf"
    owner: "{{ current_user }}"
    group: "{{ current_group }}"
    mode: "0644"
  notify: "systemd | vsh-mariadb | restarted"

- name: "provide mysqld.cnf configuration file"
  ansible.builtin.template:
    src: "ubuntu/{{ current_mariadb_service.canonical }}/mysqld.cnf.j2"
    dest: "{{ current_mariadb_service.configuration.base_path }}/etc/conf.d/mysqld.cnf"
    owner: "{{ current_user }}"
    group: "{{ current_group }}"
    mode: "0644"
  notify: "systemd | vsh-mariadb | restarted"

- name: "ensure user systemd directory exists"
  ansible.builtin.file:
    path: "{{ current_home }}/.config/systemd/user"
    state: directory
    mode: "0755"

- name: "Provide systemd service for vsh-{{ current_mariadb_service.canonical }} container"
  ansible.builtin.template:
    src: "ubuntu/systemd/mariadb.service.j2"
    dest: "{{ current_home }}/.config/systemd/user/vsh-{{ current_mariadb_service.canonical }}.service"
    owner: "{{ current_user }}"
    group: "{{ current_group }}"
    mode: "0644"
  notify: "systemd | vsh-mariadb | restarted"

- name: "provide mariadb{{ current_mariadb_service.version }} mysql client"
  ansible.builtin.template:
    src: "wrapper/mariadb.j2"
    dest: "/usr/local/bin/mariadb{{ current_mariadb_service.version }}"
    owner: root
    group: root
    mode: "0755"
  become: true

- name: "provide mariadump{{ current_mariadb_service.version }} client"
  ansible.builtin.template:
    src: "wrapper/mariadump.j2"
    dest: "/usr/local/bin/mariadump{{ current_mariadb_service.version }}"
    owner: root
    group: root
    mode: "0755"
  become: true

- name: "provide mariaadmin{{ current_mariadb_service.version }} client"
  ansible.builtin.template:
    src: "wrapper/mariaadmin.j2"
    dest: "/usr/local/bin/mariaadmin{{ current_mariadb_service.version }}"
    owner: root
    group: root
    mode: "0755"
  become: true

- name: "Ensure vsh-{{ current_mariadb_service.canonical }} is started"
  ansible.builtin.systemd:
    name: "{{ current_mariadb_service.service.name }}"
    state: started
    daemon_reload: true
    scope: "{{ current_mariadb_service.service.scope }}"

- name: Test MariaDB connection and get info
  community.mysql.mysql_info:
    login_host: "127.0.0.1"
    login_port: "{{ current_mariadb_service.configuration.ports.mariadb }}"
    login_user: root
    login_password: "{{ current_mariadb_service.configuration.default_root_password }}"
  register: mariadb_status
  until: mariadb_status is succeeded
  retries: 30
  delay: 3

- name: Stop vsh-{{ current_mariadb_service.canonical }} service after installation
  when: mariadb_status is succeeded
  ansible.builtin.systemd:
    name: "{{ current_mariadb_service.service.name }}"
    state: stopped
    scope: "{{ current_mariadb_service.service.scope }}"

- name: "Mark vsh-{{ current_mariadb_service.canonical }} as installed in the services file"
  vsh_bundle_state:
    action: "add_installed"
    canonical_names: "{{ current_mariadb_service.canonical }}"
