##
#   Copyright 2021 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "set handler_current_service fact"
  ansible.builtin.set_fact:
    handler_current_service: "{{ current_service }}"

- name: "create mariadb base directories"
  ansible.builtin.file:
    path: "{{ current_mariadb_base_directory }}"
    owner: "{{ current_user }}"
    group: "{{ current_group }}"
    mode: "0755"
    state: directory
  become: true
  with_items:
    - "{{ current_service.configuration.base_path }}"
    - "{{ current_service.configuration.base_path }}/user"
    - "{{ current_service.configuration.base_path }}/etc"
    - "{{ current_service.configuration.base_path }}/etc/mariadb.conf.d"
  loop_control:
    loop_var: current_mariadb_base_directory

- name: "Pull {{ current_service.service.name }} image"
  containers.podman.podman_image:
    name: "{{ current_service.configuration.docker_image }}"
    pull: true
    state: present

- name: "provide .my.cnf configuration file"
  ansible.builtin.template:
    src: "config/.my.cnf.j2"
    dest: "{{ current_service.configuration.base_path }}/user/.my.cnf"
    mode: "0644"

- name: "provide mysqld.cnf configuration file"
  ansible.builtin.template:
    src: "config/mysqld.cnf.j2"
    dest: "{{ current_service.configuration.base_path }}/etc/mariadb.conf.d/valet-sh.cnf"
    owner: "{{ current_user }}"
    group: "{{ current_group }}"
    mode: "0644"
  notify: "systemd | vsh-mariadb | restarted"

- name: "Provide systemd service for {{ current_service.service.name }} container"
  ansible.builtin.template:
    src: "systemd/mariadb.service.j2"
    dest: "{{ current_home }}/.config/systemd/user/{{ current_service.service.name }}.service"
    owner: "{{ current_user }}"
    group: "{{ current_group }}"
    mode: "0644"
  notify: "systemd | vsh-mariadb | restarted"

- name: "provide mariadb{{ current_service.version }} mysql client"
  ansible.builtin.template:
    src: "wrapper/mariadb.j2"
    dest: "/usr/local/bin/mariadb{{ current_service.version }}"
    owner: root
    group: root
    mode: "0755"
  become: true

- name: "provide mariadump{{ current_service.version }} client"
  ansible.builtin.template:
    src: "wrapper/mariadump.j2"
    dest: "/usr/local/bin/mariadump{{ current_service.version }}"
    owner: root
    group: root
    mode: "0755"
  become: true

- name: "provide mariaadmin{{ current_service.version }} client"
  ansible.builtin.template:
    src: "wrapper/mariaadmin.j2"
    dest: "/usr/local/bin/mariaadmin{{ current_service.version }}"
    owner: root
    group: root
    mode: "0755"
  become: true

- name: "Ensure {{ current_service.service.name }} is started"
  ansible.builtin.systemd:
    name: "{{ current_service.service.name }}"
    state: restarted
    daemon_reload: true
    scope: "{{ current_service.service.scope }}"

- name: Test MariaDB connection and get info
  community.mysql.mysql_info:
    login_host: "127.0.0.1"
    login_port: "{{ current_service.configuration.ports.tcp }}"
    login_user: root
    login_password: "{{ current_service.configuration.default_root_password }}"
  register: mariadb_status
  until: mariadb_status is succeeded
  retries: 30
  delay: 3

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers

- name: "Get desired state of {{ current_service.service.name }} from services file"
  vsh_bundle_service_state_info:
    name: "{{ current_service.canonical }}"
  register: current_service_state

- name: "If desired state is unknown, set it to enabled"
  vsh_bundle_state:
    action: "initialize_empty"
    canonical_names: "{{ current_service.canonical }}"
  when: current_service_state.state == "unknown"

- name: "Update current_service_state after initialization"
  ansible.builtin.set_fact:
    current_service_state: "{{ current_service_state | combine({'state': 'enabled'}) }}"
  when: current_service_state.state == "unknown"

- name: "Set {{ current_service.service.name }} container state"
  ansible.builtin.systemd:
    name: "{{ current_service.service.name }}"
    state: "{{ 'started' if current_service_state.state == 'enabled' else 'stopped' }}"
    enabled: "{{ 'true' if current_service_state.state == 'enabled' else 'false' }}"
    scope: "{{ current_service.service.scope }}"

- name: "Mark {{ current_service.service.name }} as installed in the services file"
  vsh_bundle_state:
    action: "installed"
    canonical_names: "{{ current_service.canonical }}"
