##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: Pull mailhog image
  containers.podman.podman_image:
    name: "{{ current_mailhog_service.configuration.docker_image }}"
    pull: true
    state: present

- name: "ensure user systemd directory exists"
  ansible.builtin.file:
    path: "{{ current_home }}/.config/systemd/user"
    state: directory
    mode: "0755"

- name: provide systemd service for mailhog container
  ansible.builtin.template:
    src: "mailhog.service.j2"
    dest: "{{ current_home }}/.config/systemd/user/{{ current_mailhog_service.service.name }}.service"
    owner: "{{ current_user }}"
    group: "{{ current_group }}"
    mode: "0644"
  notify: "systemd | vsh-mailhog | restarted"

- name: set 'cert_prefix' variable
  ansible.builtin.set_fact:
    cert_prefix: "mailhog"

- name: "generate ssl-certificate for {{ cert_prefix }}"
  ansible.builtin.include_role:
    name: certificate
    public: true

- name: provide init script for mailhog
  ansible.builtin.template:
    src: "mailhog.conf.j2"
    dest: "/etc/nginx/conf.d/mailhog.conf"
    owner: root
    group: root
    mode: "0644"
  notify: systemd | vsh-nginx | reloaded
  become: true

- name: unset 'cert_prefix' variable
  ansible.builtin.set_fact:
    cert_prefix: "{{ non_existent | default(None) }}"

- name: ensure mailhog is enabled and started
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ current_mailhog_service.service.name }}"
    enabled: true
    state: started
    scope: "{{ current_mailhog_service.service.scope }}"

- name: "Add mailhog to installed services"
  vsh_service_state:
    action: "add_installed"
    canonical_names: "{{ current_mailhog_service.canonical }}"
