##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "Ensure mailhog is stopped"
  systemd:
    daemon_reload: yes
    name: mailhog
    state: stopped
  become: true
  ignore_errors: true

- name: ensure '/etc/systemd/system/mailhog.service' file is absent
  file:
    path: "/etc/systemd/system/mailhog.service"
    state: absent
  become: true

- name: ensure '/usr/local/bin/mailhog' file is absent
  file:
    path: "/usr/local/bin/mailhog"
    state: absent
  become: true

- name: "ensure mailpit dist directory exists"
  file:
    path: "{{ mailpit_dist_dir }}"
    state: directory
    mode: '0755'

- name: "Extract mailpit binary to '{{ mailpit_dist_dir }}'"
  unarchive:
    src: "{{ mailpit_release_url }}"
    dest: "{{ mailpit_dist_dir }}"
    extra_opts: [--strip-components=1]
    remote_src: yes

- name: provide init script for mailpit
  template:
    src: "mailpit.service.j2"
    dest: "/etc/systemd/system/mailpit.service"
    owner: root
    group: root
    mode: '0644'
  notify: systemd | mailpit | restarted
  become: true

- name: set 'cert_prefix' variable
  set_fact:
    cert_prefix: "mailhog"

- name: "generate ssl-certificate for {{ cert_prefix }}"
  include_role:
    name: certificate
    public: true

- name: provide init script for mailhog
  template:
    src: "mailhog.conf.j2"
    dest: "/etc/nginx/conf.d/mailhog.conf"
    owner: root
    group: root
    mode: '0644'
  notify: systemd | nginx | reloaded
  become: true

- name: unset 'cert_prefix' variable
  set_fact:
    cert_prefix: "{{ non_existent|default(None) }}"

- name: set 'cert_prefix' variable
  set_fact:
    cert_prefix: "mailpit"

- name: "generate ssl-certificate for {{ cert_prefix }}"
  include_role:
    name: certificate
    public: true

- name: provide init script for mailpit
  template:
    src: "mailpit.conf.j2"
    dest: "/etc/nginx/conf.d/mailpit.conf"
    owner: root
    group: root
    mode: '0644'
  notify: systemd | nginx | reloaded
  become: true

- name: unset 'cert_prefix' variable
  set_fact:
    cert_prefix: "{{ non_existent|default(None) }}"

- name: ensure mailpit is enabled and started
  systemd:
    daemon_reload: yes
    name: mailpit
    enabled: true
    state: started
  become: true
