##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---
- name: Systemd | NetworkManager | started
  ansible.builtin.systemd:
    daemon_reload: true
    name: NetworkManager
    state: started
    scope: system
  become: true

- name: Systemd | NetworkManager | stopped
  ansible.builtin.systemd:
    daemon_reload: true
    name: NetworkManager
    state: stopped
    scope: system
  become: true

- name: Systemd | NetworkManager | reload
  ansible.builtin.systemd:
    daemon_reload: true
    name: NetworkManager
    state: reloaded
    scope: system
  become: true

- name: Systemd | NetworkManager | restarted
  ansible.builtin.systemd:
    daemon_reload: true
    name: NetworkManager
    state: restarted
    scope: system
  become: true

- name: brew | dnsmasq | restarted
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin_sudo }} services restart dnsmasq"

- name: brew | dnsmasq | stopped
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin_sudo }} services stop dnsmasq"

- name: brew | dnsmasq | started
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin_sudo }} services start dnsmasq"
