##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- include_tasks: "migrations/main.yml"

- name: ensure apt-transport-https is installed
  apt:
    name: apt-transport-https
    state: present
  become: true

- name: use php ppa (Ubuntu)
  apt_repository:
    repo: 'ppa:ondrej/php'
    codename: "{{ os_codename }}"
  become: true

- name: "install defined php versions"
  include_tasks: install-php.yml
    current_php="{{ php_multi_item }}"
  with_items: "{{ php_multi }}"
  loop_control:
    loop_var: php_multi_item

- name: "install php-imagick"
  apt:
    name: php-imagick
    state: present
  become: true

- name: "set default php cli version"
  alternatives:
    name: php
    path: "/usr/bin/php{{ item.version }}"
  with_items: "{{ php_multi }}"
  when: (item.default is defined) and (item.default == true)
  become: true

- name: ensure php wrapper script is up2date
  copy:
    src: "ubuntu/php-wrapper"
    dest: "/usr/local/bin/php"
    mode: '0755'
    force: true
  become: true