##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

# @TODO: migrate from ubuntu 24.04 to 26.04 - revert NetworkManger changes

- name: Run NetworkManager config for Ubuntu jammy and noble
  when:
    - os_codename != "resolute"
  block:
    - name: "enable dns resolving for .{{ dnsmasq_domain }} domain"
      ansible.builtin.template:
        src: development-domain.conf.j2
        dest: "{{ dnsmasq_conf_file }}"
      notify: Systemd | NetworkManager | reload
      become: true

    - name: "enable dns resolving for .{{ dnsmasq_vsh_service_domain }} domain"
      ansible.builtin.copy:
        content: |
          address=/.{{ dnsmasq_vsh_service_domain }}/127.0.0.1
        dest: "/etc/NetworkManager/dnsmasq.d/vsh.conf"
      notify: Systemd | NetworkManager | reload
      become: true

    - name: enable dnsmasq in NetworkManager
      ansible.builtin.lineinfile:
        path: "/etc/NetworkManager/NetworkManager.conf"
        insertafter: "^\\[main\\]"
        line: "dns=dnsmasq"
      notify: Systemd | NetworkManager | reload
      become: true

    - name: "set symlink /etc/resolv.conf to /var/run/NetworkManager/resolv.conf on Ubuntu non-resolute"
      ansible.builtin.file:
        src: "/var/run/NetworkManager/resolv.conf"
        dest: "/etc/resolv.conf"
        state: link
      notify: Systemd | NetworkManager | reload
      become: true

- name: Run systemd-resolved config for Ubuntu resolute
  when:
    - os_codename == "resolute"
  block:
    - name: ensure dnsmasq is installed
      apt:
        name: dnsmasq
        state: present
      become: true

    - name: "ensure dnsmasq listens to port 5353"
      ansible.builtin.lineinfile:
        path: "/etc/dnsmasq.conf"
        line: "port=5353"
        state: present
      become: true
      notify: Systemd | dnsmasq | restarted

    - name: "ensure domain '*.{{ dnsmasq_domain }}' is handled by local dns"
      ansible.builtin.copy:
        dest: "/etc/dnsmasq.d/{{ dnsmasq_domain }}.conf"
        content: |
          address=/.{{ dnsmasq_domain }}/127.0.0.1
      become: true
      notify: Systemd | dnsmasq | restarted

    - name: "ensure domain '*.{{ dnsmasq_vsh_service_domain }}' is handled by local dns"
      ansible.builtin.copy:
        dest: "/etc/dnsmasq.d/{{ dnsmasq_vsh_service_domain }}.conf"
        content: |
          address=/.{{ dnsmasq_vsh_service_domain }}/127.0.0.1
      become: true
      notify: Systemd | dnsmasq | restarted

    - name: "ensure '/etc/systemd/resolved.conf.d' exists"
      ansible.builtin.file:
        path: "/etc/systemd/resolved.conf.d"
        state: directory
        mode: "0755"
      become: true

    - name: "ensure domain '*.{{ dnsmasq_domain }}' is handled by local dns"
      ansible.builtin.copy:
        dest: "/etc/systemd/resolved.conf.d/{{ dnsmasq_domain }}.conf"
        content: |
          [Resolve]
          DNS=127.0.0.1:5353
          Domains=~{{ dnsmasq_domain }}
      become: true
      notify: Systemd | SystemdResolved | restarted

    - name: "ensure domain '*.{{ dnsmasq_vsh_service_domain }}' is handled by local dns"
      ansible.builtin.copy:
        dest: "/etc/systemd/resolved.conf.d/{{ dnsmasq_vsh_service_domain }}.conf"
        content: |
          [Resolve]
          DNS=127.0.0.1:5353
          Domains=~{{ dnsmasq_vsh_service_domain }}
      become: true
      notify: Systemd | SystemdResolved | restarted

    - name: "set symlink /etc/resolv.conf to '../run/systemd/resolve/stub-resolv.conf on Ubuntu resolute'"
      ansible.builtin.file:
        src: "../run/systemd/resolve/stub-resolv.conf"
        dest: "/etc/resolv.conf"
        state: link
      notify: Systemd | SystemdResolved | restarted
      become: true

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers

- name: "Mark dnsmasq as installed in the services file"
  vsh_bundle_state:
    action: "installed"
    canonical_names: "dnsmasq"
