##
#   Copyright 2025 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: Uninstall NetworkManager dnsmasq config for Ubuntu jammy and noble
  when:
    - os_codename != "resolute"
  block:
    - name: "remove dnsmasq config for .{{ dnsmasq_domain }} domain"
      ansible.builtin.file:
        path: "{{ dnsmasq_conf_file }}"
        state: absent
      notify: Systemd | NetworkManager | reload
      become: true

    - name: "remove dnsmasq config for .{{ dnsmasq_vsh_service_domain }} domain"
      ansible.builtin.file:
        path: "/etc/NetworkManager/dnsmasq.d/vsh.conf"
        state: absent
      notify: Systemd | NetworkManager | reload
      become: true

    - name: "disable dnsmasq in NetworkManager"
      ansible.builtin.lineinfile:
        path: "/etc/NetworkManager/NetworkManager.conf"
        line: "dns=dnsmasq"
        state: absent
      notify: Systemd | NetworkManager | reload
      become: true

- name: Uninstall systemd-resolved dnsmasq config for Ubuntu resolute
  when:
    - os_codename == "resolute"
  block:
    - name: "stop and disable dnsmasq service"
      ansible.builtin.systemd:
        name: dnsmasq
        state: stopped
        enabled: no
      become: true
      ignore_errors: yes

    - name: "remove dnsmasq domain config .{{ dnsmasq_domain }}"
      ansible.builtin.file:
        path: "/etc/dnsmasq.d/{{ dnsmasq_domain }}.conf"
        state: absent
      become: true

    - name: "remove dnsmasq domain config .{{ dnsmasq_vsh_service_domain }}"
      ansible.builtin.file:
        path: "/etc/dnsmasq.d/{{ dnsmasq_vsh_service_domain }}.conf"
        state: absent
      become: true

    - name: "remove dnsmasq port config"
      ansible.builtin.lineinfile:
        path: "/etc/dnsmasq.conf"
        line: "port=5353"
        state: absent
      become: true

    - name: "remove dnsmasq interfaces config"
      ansible.builtin.lineinfile:
        path: "/etc/dnsmasq.conf"
        regexp: "^interface="
        state: absent
      become: true

    - name: "remove dnsmasq bind-interfaces config"
      ansible.builtin.lineinfile:
        path: "/etc/dnsmasq.conf"
        line: "bind-interfaces"
        state: absent
      become: true

    - name: "remove systemd-resolved domain config .{{ dnsmasq_domain }}"
      ansible.builtin.file:
        path: "/etc/systemd/resolved.conf.d/{{ dnsmasq_domain }}.conf"
        state: absent
      notify: Systemd | SystemdResolved | restarted
      become: true

    - name: "remove systemd-resolved domain config .{{ dnsmasq_vsh_service_domain }}"
      ansible.builtin.file:
        path: "/etc/systemd/resolved.conf.d/{{ dnsmasq_vsh_service_domain }}.conf"
        state: absent
      notify: Systemd | SystemdResolved | restarted
      become: true

    - name: "uninstall dnsmasq package"
      apt:
        name: dnsmasq
        state: absent
      become: true

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers

- name: "Mark dnsmasq as uninstalled in the services file"
  vsh_bundle_state:
    action: "uninstalled"
    canonical_names: "dnsmasq"

- name: "Mark dnsmasq as disabled in the services file"
  vsh_bundle_state:
    action: "disabled"
    canonical_names: "dnsmasq"
