##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: Uninstall valkey-tools
  ansible.builtin.apt:
    name: "valkey-tools"
    state: absent
  become: true

- name: Ensure that valkey container is stopped
  ansible.builtin.systemd:
    name: "{{ current_valkey_service.service.name }}"
    state: stopped
    daemon_reload: true
    scope: "{{ current_valkey_service.service.scope }}"
  ignore_errors: true

- name: Remove valkey container
  containers.podman.podman_container:
    name: "vsh-{{ current_valkey_service.canonical }}"
    state: absent

- name: Remove valkey volume
  containers.podman.podman_volume:
    name: "vsh-{{ current_valkey_service.canonical }}"
    state: absent
  when: "'--purge' in valet_cli_opts"

- name: Remove valkey systemd service
  ansible.builtin.file:
    path: "{{ current_home }}/.config/systemd/user/{{ current_valkey_service.service.name }}.service"
    state: absent

- name: "Remove vsh-{{ current_valkey_service.canonical }} default.target.wants symlink"
  ansible.builtin.file:
    path: "{{ current_home }}/.config/systemd/user/default.target.wants/{{ current_valkey_service.service.name }}.service"
    state: absent

- name: Remove valkey image
  containers.podman.podman_image:
    name: "{{ current_valkey_service.configuration.docker_image }}"
    state: absent
    force: true
  when: "'--purge' in valet_cli_opts"

- name: "Remove vsh-{{ current_valkey_service.canonical }} from installed services"
  vsh_service_state:
    action: "remove_installed"
    canonical_names: "{{ current_valkey_service.canonical }}"
