##
#   Copyright 2025 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "uninstall » check services.yml for installed services"
  ansible.builtin.include_vars:
    file: "{{ valet_etc_services_file}}"
    name: valet_all_services

- name: Debug valet_all_services
  ansible.builtin.debug:
    var: valet_all_services

- name: "uninstall » if no services found fail"
  ansible.builtin.fail:
    msg: "No installed services/packages found to uninstall!"
  when: >-
    valet_all_services.services.installed is none  or
    valet_all_services.packages.installed is none

- name: "set all services and packages to uninstall"
  ansible.builtin.set_fact:
    valet_uninstall_all: "{{ valet_all_services.bundles.services.installed.keys() | list + valet_all_services.bundles.packages.installed.keys() | list }}"

- name: Debug set to uninstall
  ansible.builtin.debug:
    var: valet_uninstall_all

- name: "resolve requested services"
  vsh_bundle_resolver:
    name: "{{ valet_uninstall_all }}"
    current_os: "{{ current_os }}"
  register: vsh_resolver

- name: "uninstall services"
  ansible.builtin.include_role:
    name: "{{ role_item }}"
    public: true
  vars:
    valet_resolved_service:
      services: "{{ vsh_resolver.services | selectattr('role_name', 'equalto', role_item) | list }}"
  loop: "{{ vsh_resolver.services | map(attribute='role_name') | unique | list }}"
  loop_control:
    loop_var: role_item
  when: vsh_resolver.services | length > 0

- name: "uninstall packages"
  ansible.builtin.include_role:
    name: "{{ role_item }}"
    public: true
  vars:
    valet_resolved_service:
      packages: "{{ vsh_resolver.packages | selectattr('role_name', 'equalto', role_item) | list }}"
  loop: "{{ vsh_resolver.packages | map(attribute='role_name') | unique | list }}"
  loop_control:
    loop_var: role_item
  when: vsh_resolver.packages | length > 0
