##
#   Copyright 2023 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "Templates » fallback | provide nginx fallback vhost for {{ link_name }}.{{ development_tld }}"
  ansible.builtin.template:
    src: "nginx/fallback.conf.j2"
    dest: "{{ valet_sh_prefix }}/etc/nginx/conf.d/{{ link_name }}.{{ development_tld }}.conf"
    mode: '0644'
  notify: brew | nginx | restarted

- name: "Templates » fallback | set var 'nginx_template' when no app was found"
  ansible.builtin.set_fact:
    nginx_template: "Fallback"
