##
#   Copyright 2023 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "Templates » magento1 | check for magento1 project"
  ansible.builtin.stat:
    path: "{{ valet_current_path }}/app/code/core/Mage"
  register: m1_checker_obj

- name: "Block"
  when: m1_checker_obj.stat.exists
  block:
    - name: "Check for multidomain configuration in .valet-sh.yml file"
      ansible.builtin.set_fact:
        valet_sh_project_multidomain_config: "{{ valet_sh_project_vars.instance.multidomain }}"
      when:
        - valet_sh_project_vars is defined
        - valet_sh_project_vars.instance is defined
        - valet_sh_project_vars.instance.multidomain is defined

    - name: "Templates » magento1 | provide nginx vhost configuration for {{ link_name }}.{{ development_tld }}"
      ansible.builtin.template:
        src: "nginx/magento1.conf.j2"
        dest: "{{ valet_sh_prefix }}/etc/nginx/conf.d/{{ link_name }}.{{ development_tld }}.conf"
        mode: '0644'
      notify: brew | nginx | restarted

    - name: "Templates » magento1 | set var 'template_found' when m1 instance was found"
      ansible.builtin.set_fact:
        template_found: true
        nginx_template: "Magento 1"
