##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: Pull rabbitmq-server image
  containers.podman.podman_image:
    name: "docker.io/rabbitmq:3.12.14-management"
    pull: true
    state: present

- name: "ensure user systemd directory exists"
  file:
    path: "{{ current_home }}/.config/systemd/user"
    state: directory
    mode: '0755'

- name: Provide systemd service for rabbitmq-server container
  ansible.builtin.template:
    src: "systemd/rabbitmq-server.service.j2"
    dest: "{{ current_home }}/.config/systemd/user/rabbitmq-server.service"
    owner: "{{ current_user }}"
    group: "{{ current_group }}"
    mode: '0644'
  notify: "systemd | rabbitmq-server | restarted"

- name: ensure rabbitmq-server is running and enabled
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: true
    scope: user

- name: set 'cert_prefix' variable
  set_fact:
    cert_prefix: "rabbitmq"

- name: "generate ssl-certificate for rabbitmq.{{ development_tld }}"
  include_role:
    name: certificate
    public: true

- name: provide nginx vhost configuration for rabbitmq management plugin
  template:
    src: "rabbitmq.conf.j2"
    dest: "/etc/nginx/conf.d/rabbitmq.conf"
    owner: root
    group: root
    mode: '0644'
  notify: systemd | nginx | reloaded
  become: true

- name: unset 'cert_prefix' variable
  set_fact:
    cert_prefix: "{{ non_existent|default(None) }}"
