##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: ensure rabbitmq-server is installed
  apt:
    name: rabbitmq-server
    state: present
  become: true

- name: ensure rabbitmq-server is running and enabled
  service:
    name: rabbitmq-server
    state: started
    enabled: yes
  become: true

- name: Ensure the rabbitmq_management plugin is enabled
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
  become: true

- name: "generate ssl-certificate for rabbitmq.{{ development_tld }}"
  include_role:
    name: certificate
    public: true
  vars:
    cert_prefix: rabbitmq

- name: "ensure systemd rabbitmq-server config directory exists"
  file:
    path: "/etc/systemd/system/rabbitmq-server.service.d/"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: ensure rabbitmq-server.service override.conf is up2date
  template:
    src: "rabbitmq-server.service.j2"
    dest: "/etc/systemd/system/rabbitmq-server.service.d/override.conf"
    owner: root
    group: root
    mode: '0644'
  notify: systemd | rabbitmq-server | full-restart
  become: true

- name: provide nginx vhost configuration for rabbitmq management plugin
  template:
    src: "rabbitmq.conf.j2"
    dest: "/etc/nginx/conf.d/rabbitmq.conf"
    owner: root
    group: root
    mode: '0644'
  notify: systemd | nginx | reloaded
  become: true

