##
#   Copyright 2021 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---
- name: systemd | daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: "systemd | vsh-mariadb | started"
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ mariadb_item.service.name }}"
    state: started
    scope: "{{ mariadb_item.service.scope }}"
  loop: "{{ vsh_resolver.services | selectattr('canonical', 'match', '^mariadb.*') }}"
  loop_control:
    loop_var: mariadb_item
  listen: "systemd | vsh-mariadb | started"

- name: "systemd | vsh-mariadb | stopped"
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ mariadb_item.service.name }}"
    state: stopped
    scope: "{{ mariadb_item.service.scope }}"
  loop: "{{ vsh_resolver.services | selectattr('canonical', 'match', '^mariadb.*') }}"
  loop_control:
    loop_var: mariadb_item
  listen: "systemd | vsh-mariadb | stopped"

- name: "systemd | vsh-mariadb | restarted"
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ mariadb_item.service.name }}"
    state: restarted
    scope: "{{ mariadb_item.service.scope }}"
  loop: "{{ vsh_resolver.services | selectattr('canonical', 'match', '^mariadb.*') }}"
  loop_control:
    loop_var: mariadb_item
  listen: "systemd | vsh-mariadb | restarted"

- name: "systemd | vsh-mariadb | reloaded"
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ mariadb_item.service.name }}"
    state: restarted
    scope: "{{ mariadb_item.service.scope }}"
  loop: "{{ vsh_resolver.services | selectattr('canonical', 'match', '^mariadb.*') }}"
  loop_control:
    loop_var: mariadb_item
  listen: "systemd | vsh-mariadb | reloaded"

- name: brew | vsh-mariadb104 | started
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services start vsh-mariadb104"
- name: brew | vsh-mariadb104 | stopped
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services stop vsh-mariadb104"
- name: brew | vsh-mariadb104 | restarted
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services restart vsh-mariadb104"
- name: brew | vsh-mariadb106 | started
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services start vsh-mariadb106"
- name: brew | vsh-mariadb106 | stopped
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services stop vsh-mariadb106"
- name: brew | vsh-mariadb106 | restarted
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services restart vsh-mariadb106"
- name: brew | vsh-mariadb114 | started
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services start vsh-mariadb114"
- name: brew | vsh-mariadb114 | stopped
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services stop vsh-mariadb114"
- name: brew | vsh-mariadb114 | restarted
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services restart vsh-mariadb114"
