##
#   Copyright 2024 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: fail when php version is not set
  ansible.builtin.fail:
    msg: "version variable is not defined"
  when: (current_php.version is not defined) or (current_php.version|length == 0)

- name: set php_version variable
  ansible.builtin.set_fact:
    php_version: "{{ current_php.version }}"

- name: "set php_version variable"
  ansible.builtin.set_fact:
    php_package_name: "vsh-php{{ php_version | replace('.', '') }}"

- name: "ensure {{ php_package_name }} is installed"
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} install {{ php_package_name }}"

- name: "ensure directory '{{ valet_sh_prefix }}/etc/{{ php_package_name }}/mods-available' exists"
  ansible.builtin.file:
    path: "{{ valet_sh_prefix }}/etc/{{ php_package_name }}/mods-available"
    state: directory
    mode: '0755'

- name: ensure xdebug.ini configuration is deleted
  ansible.builtin.file:
    path: "{{ valet_sh_prefix }}/etc/{{ php_package_name }}/mods-available/xdebug.ini"
    state: absent
  become: true

- name: ensure xdebug2 config is deployed
  ansible.builtin.template:
    src: "macos/xdebug2.ini.j2"
    dest: "{{ valet_sh_prefix }}/etc/{{ php_package_name }}/mods-available/xdebug2.ini"
    mode: '0644'
  when: 'php_version in native_xdebug2_versions'

- name: ensure xdebug3 config is deployed
  ansible.builtin.template:
    src: "macos/xdebug3.ini.j2"
    dest: "{{ valet_sh_prefix }}/etc/{{ php_package_name }}/mods-available/xdebug3.ini"
    mode: '0644'
  when: 'php_version in native_xdebug3_versions'

- name: ensure compiled xdebug2 config is deployed
  ansible.builtin.template:
    src: "macos/xdebug2-compiled.ini.j2"
    dest: "{{ valet_sh_prefix }}/etc/{{ php_package_name }}/mods-available/xdebug2.ini"
    mode: '0644'
  when: 'php_version in compiled_xdebug2_versions'

- name: "ensure imagick config file exists"
  ansible.builtin.lineinfile:
    path: "{{ valet_sh_prefix }}/etc/{{ php_package_name }}/mods-available/imagick.ini"
    line: 'extension=imagick.so'
    mode: '0644'
    create: true

- name: "ensure imagick module is enabled"
  ansible.builtin.file:
    src: "{{ valet_sh_prefix }}/etc/{{ php_package_name }}/mods-available/imagick.ini"
    dest: "{{ valet_sh_prefix }}/etc/{{ php_package_name }}/conf.d/imagick.ini"
    state: link
  notify: "brew | {{ current_php }} | restarted"

- name: get stat for error.log file
  ansible.builtin.stat:
    path: "{{ php_error_log_path }}"
  register: php_error_log_file_obj

- name: create php_errors.log file
  ansible.builtin.file:
    dest: "{{ php_error_log_path }}"
    state: "{{ 'file' if php_error_log_file_obj.stat.exists else 'touch' }}"
    mode: '0755'
  become: true

- name: set PATH env variable
  ansible.builtin.lineinfile:
    path: "{{ valet_sh_prefix }}/etc/{{ php_package_name }}/php-fpm.d/www.conf"
    regexp: ';env[PATH] = /usr/local/bin:/usr/bin:/bin'
    line: "env[PATH] = /usr/local/bin:/usr/bin:/bin"
  when: current_php != "vsh-php56"

- name: set PATH env variable for php5.6
  ansible.builtin.lineinfile:
    path: "{{ valet_sh_prefix }}/etc/{{ current_php }}/php-fpm.conf"
    regexp: ';env[PATH] = /usr/local/bin:/usr/bin:/bin'
    line: "env[PATH] = /usr/local/bin:/usr/bin:/bin"
  when: current_php == "vsh-php56"

- name: ensure php configuration is up2date
  ansible.builtin.template:
    src: "macos/valet-sh.conf.j2"
    dest: "{{ valet_sh_prefix }}/etc/{{ php_package_name }}/conf.d/95-valet-sh.ini"
    mode: '0644'
  notify: "brew | {{ current_php }} | restarted"

- name: "get stat for '/usr/local/bin/default-php'"
  ansible.builtin.stat:
    path: "/usr/local/bin/default-php"
  register: php_default_symlink_obj

- name: "create symlink for default php"
  ansible.builtin.file:
    src: "/usr/local/bin/php7.3"
    dest: "/usr/local/bin/default-php"
    state: link
    force: true
  when: php_default_symlink_obj.stat.islnk is not defined

- name: ensure php wrapper script is up2date
  ansible.builtin.copy:
    src: "macos/php-wrapper"
    dest: "{{ valet_sh_prefix }}/bin/php"
    mode: '0755'
    force: true
