##
#   Copyright 2025 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: set php_version variable
  ansible.builtin.set_fact:
    php_version: "{{ current_service.version }}"

- name: ensure service is stopped
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services stop vsh-{{ current_service.canonical }}"

- name: "ensure '{{ current_service.service.name }}' is absent"
  homebrew:
    name: "{{ current_service.service.name }}"
    state: absent

- name: ensure php configuration is absent
  ansible.builtin.file:
    path: "{{ php_version_path_item }}"
    state: absent
  with_items:
    - "{{ valet_sh_homebrew_prefix }}/etc/{{ current_service.service.name }}"
  loop_control:
    loop_var: php_version_path_item
  become: true

- name: "Remove vsh-{{ current_service.canonical }} from installed services"
  vsh_bundle_state:
    action: "uninstalled"
    canonical_names: "{{ current_service.canonical }}"
