---

service:
  name:
    ubuntu: "vsh-opensearch1"
    mac: "vsh-opensearch1"
  scope:
    ubuntu: "user"
    mac: "user"
  provider:
    ubuntu: "systemd"
    mac: "container"

configuration:
  docker_image: "docker.io/opensearchproject/opensearch:1.3.20"
  limits:
    memory: "4g"
    cpus: "2"
  ports:
    http: 9221
    transport: 9321
  base_path: "/usr/local/valet-sh/packages/opensearch1"
  plugins:
    default_plugins:
      - name: "analysis-phonetic"
      - name: "analysis-icu"
    install_command: "/usr/share/opensearch/bin/opensearch-plugin install"
    list_command: "/usr/share/opensearch/bin/opensearch-plugin list"
