---

service:
  name:
    ubuntu: "vsh-opensearch2"
    mac: "vsh-opensearch2"
  scope:
    ubuntu: "user"
    mac: "user"

configuration:
  docker_image: "docker.io/opensearchproject/opensearch:2.19.5"
  limits:
    memory: "4g"
    cpus: "2"
  ports:
    http: 9222
    transport: 9322
  base_path: "/usr/local/valet-sh/packages/opensearch2"
  plugins:
    default_plugins:
      - name: "analysis-phonetic"
      - name: "analysis-icu"
    install_command: "/usr/share/opensearch/bin/opensearch-plugin install"
    list_command: "/usr/share/opensearch/bin/opensearch-plugin list"
