---

service:
  name:
    ubuntu: "vsh-opensearch3"
    mac: "vsh-opensearch3"
  scope:
    ubuntu: "user"
    mac: "user"

configuration:
  docker_image: "docker.io/opensearchproject/opensearch:3.6.0"
  limits:
    memory: "4g"
    cpus: "2"
  ports:
    http: 9223
    transport: 9323
  base_path: "/usr/local/valet-sh/packages/opensearch3"
  plugins:
    default_plugins:
      - name: "analysis-phonetic"
      - name: "analysis-icu"
    install_command: "/usr/share/opensearch/bin/opensearch-plugin install {{ name }}"
    list_command: "/usr/share/opensearch/bin/opensearch-plugin list"
