##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "check for multiple versions of same service with default action"
  debug:
    msg: "Cannot set multiple versions of {{ item.service_name }} as default. Only one version per service can be default."
  when:
    - (valet_all_services | selectattr('service_name', 'equalto', item.service_name) | list | length) > 1
  loop: "{{ valet_all_services }}"

- name: "actions » default | check if service is defaultable"
  fail:
    msg: "Service {{ item.service_name }} is not defaultable. Cannot set as default."
  when:
    - (valet_all_services | selectattr('defaultable', 'equalto', false) | list | length) > 0
  loop: "{{ valet_all_services }}"

- name: "actions » default | include service specific default tasks"
  ansible.builtin.include_tasks: "ubuntu/actions/defaults/{{ service_map[item.service_name] | default(item.service_name) }}.yml"
  loop: "{{ valet_all_services }}"
  vars:
    service_map:
      mariadb: mysql
      opensearch: elasticsearch

- name: "actions » default | set service as default using vsh_service_state module"
  vsh_service_state:
    action: "set_default"
    service_name: "{{ item.service_name }}"
    canonical_names: "{{ item.canonical }}"
  loop: "{{ valet_all_services }}"
