##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "actions » enable | fail when service defintion is not defined"
  ansible.builtin.fail:
    msg: "service definition is not defined cannot enable service"
  when: service_item.service is not defined

- name: "actions » enable | set {{ service_item.service_item.name }} as enabled using vsh_bundle_state module"
  vsh_bundle_state:
    action: "enabled"
    canonical_names: "{{ service_item.canonical }}"

- name: "actions » enable | enable {{ service_item.service.name }} service"
  ansible.builtin.systemd:
    name: "{{ service_item.service.name }}"
    state: started
    enabled: true
    scope: "{{ service_item.service.scope }}"
    daemon_reload: true
  become: "{{ service_item.service.scope == 'system' }}"
