##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "actions » restart | include sub-restart-all task when service name is all"
  ansible.builtin.include_tasks: "ubuntu/actions/sub-restart-all.yml"
  when: "'--all' in valet_cli_opts"

- name: "actions » restart | restart {{ service_item.service.name if service_item is defined else 'service' }} service"
  ansible.builtin.systemd:
    name: "{{ service_item.service.name }}"
    state: restarted
    scope: "{{ service_item.service.scope }}"
    daemon_reload: true
  become: "{{ service_item.service.scope == 'system' }}"
  when: "'--all' not in valet_cli_opts"
