---

service:
  name:
    ubuntu: "php7.0-fpm"
    mac: "vsh-php70"
  scope:
    ubuntu: "system"
    mac: "user"

configuration:
  package_names:
    ubuntu: ["php7.0-fpm", "php7.0-cli"]
    mac: ["php7.0-fpm", "php7.0-cli"]
  config_paths:
    ubuntu: ["/etc/php/7.0"]
