---

service:
  name:
    ubuntu: "php7.1-fpm"
    mac: "vsh-php71"
  scope:
    ubuntu: "system"
    mac: "user"

configuration:
  package_names:
    ubuntu: ["php7.1-fpm", "php7.1-cli"]
    mac: ["php7.1-fpm", "php7.1-cli"]
  config_paths:
    ubuntu: ["/etc/php/7.1"]
