---

service:
  name:
    ubuntu: "php7.4-fpm"
    mac: "vsh-php74"
  scope:
    ubuntu: "system"
    mac: "user"

configuration:
  package_names:
    ubuntu: ["php7.4-fpm", "php7.4-cli"]
    mac: ["php7.4-fpm", "php7.4-cli"]
  config_paths:
    ubuntu: ["/etc/php/7.4"]
