---

service:
  name:
    ubuntu: "php8.1-fpm"
    mac: "vsh-php81"
  scope:
    ubuntu: "system"
    mac: "user"

configuration:
  package_names:
    ubuntu: ["php8.1-fpm", "php8.1-cli"]
    mac: ["php8.1-fpm", "php8.1-cli"]
  config_paths:
    ubuntu: ["/etc/php/8.1"]
