---

service:
  name:
    ubuntu: "php8.3-fpm"
    mac: "vsh-php83"
  scope:
    ubuntu: "system"
    mac: "user"

configuration:
  package_names:
    ubuntu: ["php8.3-fpm", "php8.3-cli"]
    mac: ["php8.3-fpm", "php8.3-cli"]
  config_paths:
    ubuntu: ["/etc/php/8.3"]
