##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "systemd | vsh-rabbitmq | started"
  ansible.builtin.systemd:
    daemon_reload: true
    name: "vsh-{{ handler_current_service.canonical }}"
    state: started
    scope: "{{ handler_current_service.service.scope }}"

- name: "systemd | vsh-rabbitmq | stopped"
  ansible.builtin.systemd:
    daemon_reload: true
    name: "vsh-{{ handler_current_service.canonical }}"
    state: stopped
    scope: "{{ handler_current_service.service.scope }}"

- name: "systemd | vsh-rabbitmq | restarted"
  ansible.builtin.systemd:
    daemon_reload: true
    name: "vsh-{{ handler_current_service.canonical }}"
    state: restarted
    scope: "{{ handler_current_service.service.scope }}"


- name: "LaunchAgent | vsh-rabbitmq | daemon-reload"
  vsh_launchagent:
    label: "sh.valet.{{ rabbitmq_item.service.name }}"
    daemon_reload: true
  loop: "{{ vsh_resolver.services | selectattr('canonical', 'match', '^rabbitmq.*') }}"
  loop_control:
    loop_var: rabbitmq_item
  listen: "LaunchAgent | vsh-rabbitmq | daemon-reload"

- name: "LaunchAgent | vsh-rabbitmq | started"
  vsh_launchagent:
    label: "sh.valet.{{ rabbitmq_item.service.name }}"
    state: started
  loop: "{{ vsh_resolver.services | selectattr('canonical', 'match', '^rabbitmq.*') }}"
  loop_control:
    loop_var: rabbitmq_item
  listen: "LaunchAgent | vsh-rabbitmq | started"

- name: "LaunchAgent | vsh-rabbitmq | stopped"
  vsh_launchagent:
    label: "sh.valet.{{ rabbitmq_item.service.name }}"
    state: stopped
  loop: "{{ vsh_resolver.services | selectattr('canonical', 'match', '^rabbitmq.*') }}"
  loop_control:
    loop_var: rabbitmq_item
  listen: "LaunchAgent | vsh-rabbitmq | stopped"

- name: "LaunchAgent | vsh-rabbitmq | restarted"
  vsh_launchagent:
    label: "sh.valet.{{ rabbitmq_item.service.name }}"
    state: restarted
  loop: "{{ vsh_resolver.services | selectattr('canonical', 'match', '^rabbitmq.*') }}"
  loop_control:
    loop_var: rabbitmq_item
  listen: "LaunchAgent | vsh-rabbitmq | restarted"
