##
#   Copyright 2023 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "partials » check-vars | fail when valet_current_path is not defined"
  fail:
    msg: "valet_current_path is not defined"
  when: valet_current_path is not defined

- name: "partials » check-vars | set working dir name"
  set_fact:
    valet_working_dir: "{{ valet_current_path | basename }}"

- name: "partials » check-vars | fail when valet_action variable is empty"
  fail:
    msg: "no action defined"
  when: valet_action | length == 0

- name: "workflows » aem » check-vars | set default path to project source"
  set_fact:
    valet_sh_project_src_path: "{{ valet_current_path }}"

- name: "workflows » aem » check-vars | set path to project source"
  set_fact:
    valet_sh_project_src_path: "{{ valet_current_path }}/{{ valet_sh_project_vars.instance.path }}"
  when:
    - valet_sh_project_vars.instance is defined
    - valet_sh_project_vars.instance.path is defined
