##
#   Copyright 2023 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "Ensure mailhog is installed"
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} install mailhog"
  notify: Brew | mailhog | restart

- name: "Generate ssl-certificate for {{ cert_prefix }}"
  ansible.builtin.include_role:
    name: certificate
    public: true
  vars:
    cert_prefix: mailhog

- name: Provide init script for mailhog
  ansible.builtin.template:
    src: "mailhog.conf.j2"
    dest: "{{ valet_sh_prefix }}/etc/nginx/conf.d/mailhog.conf"
    mode: '0644'
  notify: Brew | nginx | restarted

- name: Brew | mailhog | restart
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services restart mailhog"
