##
#   Copyright 2021 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---
# - ansible.builtin.include_tasks: composer1.yml

# - ansible.builtin.include_tasks: composer2.yml
#
- name: Debug current_composer_service
  ansible.builtin.debug:
    var: current_composer_service

- name: "ensure composer-{{ current_composer_service.version }} is installed"
  ansible.builtin.get_url:
    url: https://getcomposer.org/composer-{{ current_composer_service.version }}.phar
    dest: "{{ current_composer_service.configuration.phar_bin }}"
    owner: "{{ current_user }}"
    group: "{{ current_group }}"
    mode: "0755"
    force: true
  become: true

- name: "ensure composer{{ current_composer_service.version }} script is up2date"
  ansible.builtin.template:
    src: "composer{{ current_composer_service.version }}.j2"
    dest: "{{ current_composer_service.configuration.bin_path_default }}"
    mode: "0755"
    force: true
  become: true

- name: ensure composer wrapper script is up2date
  ansible.builtin.template:
    src: "composer-wrapper.j2"
    dest: "/usr/local/bin/composer"
    mode: "0755"
  become: true

- name: "get stat for '/usr/local/bin/composer-php'"
  ansible.builtin.stat:
    path: "/usr/local/bin/default-composer"
  register: composer_default_symlink_obj

- name: "create symlink for default php"
  ansible.builtin.file:
    src: "/usr/local/bin/composer1"
    dest: "/usr/local/bin/default-composer"
    state: link
    force: true
  become: true
  when: composer_default_symlink_obj.stat.islnk is not defined

- name: "Mark composer{{ current_composer_service.version }} as installed in the bundle file"
  vsh_bundle_state:
    action: "add_installed"
    name: "composer"
    canonical_names: "{{ current_composer_service.canonical }}"
