##
#   Copyright 2023 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "workflows » neos » services » node | set default node version"
  ansible.builtin.set_fact:
    valet_sh_node_version: "{{ valet_sh_default_node_version }}"

- name: "workflows » neos » services » node | override node version based on .valet-sh.yml"
  ansible.builtin.set_fact:
    valet_sh_node_version: "{{ valet_sh_project_vars.services.node.version }}"
  when:
    - valet_sh_project_vars.services is defined
    - valet_sh_project_vars.services.node is defined
    - valet_sh_project_vars.services.node.version is defined

# ansible cannot change any setting of the current shell as every "shell" or "command" module call will be executed in a
# new separated shell. The command "nvm install 10" don't change the node version for the current user shell, but only for
# the shell currently started by ansible for the module execution
