---

service:
  name:
    ubuntu: "vsh-redis6"
    mac: "vsh-redis6"
  scope:
    ubuntu: "user"
    mac: "user"
  provider:
    ubuntu: "systemd"
    mac: "container"

configuration:
  docker_image: "docker.io/library/redis:6"
  ports:
    tcp: 6379
  base_path: "/usr/local/valet-sh/packages/redis6"
