---

service:
  name:
    ubuntu: "vsh-redis7"
    mac: "vsh-redis7"
  scope:
    ubuntu: "user"
    mac: "user"
  provider:
    ubuntu: "systemd"
    mac: "container"

configuration:
  docker_image: "docker.io/library/redis:7"
  ports:
    tcp: 6381
  base_path: "/usr/local/valet-sh/packages/redis7"
