---

service:
  name:
    ubuntu: "vsh-redis7"
    mac: "vsh-redis7"
  scope:
    ubuntu: "user"
    mac: "user"

configuration:
  docker_image: "docker.io/library/redis:7"
  ports:
    redis: 6380
  base_path: "/usr/local/valet-sh/packages/redis7"