##
#   Copyright 2023 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "Block"
  when: valet_opt_flag_clean is defined and valet_opt_flag_clean|bool
  block:
    - name: "workflows » magento2 » project-install | clear cache folders"
      ansible.builtin.file:
        path: "{{ valet_sh_project_src_path }}/{{ current_project_cache_path_item }}"
        state: absent
      with_items:
        - "var/full_page_cache/"
        - "var/cache/"
        - "var/page_cache/"
        - "generated/"
        - "var/generation/"
        - "var/view_preprocessed/"
        - "pub/static/"
        - "vendor"
      loop_control:
        loop_var: current_project_cache_path_item

- name: "workflows » magento2 » project-install | run composer install in project source path when defined in .valet-sh.yml"
  ansible.builtin.command: "{{ php_bin }} {{ composer_bin }} install -n"
  args:
    chdir: "{{ valet_sh_project_src_path }}"
    removes: "composer.json"
  when: valet_current_path != valet_sh_project_src_path

- name: "workflows » magento2 » project-install | run composer install in current dir"
  ansible.builtin.command: "{{ php_bin }} {{ composer_bin }} install -n"
  args:
    chdir: "{{ valet_current_path }}"
    removes: "composer.json"

- name: "Block"
  when: valet_sh_config.default_nvm is not defined or valet_sh_config.default_nvm != "volta"
  block:
    - name: "workflows » magento2 » project-install | run npm install in current dir"
      ansible.builtin.shell: "source {{ current_home }}/.nvm/nvm.sh && nvm install {{ valet_sh_node_version }} && /usr/bin/env npm install"
      args:
        chdir: "{{ valet_current_path }}"
        executable: /bin/bash
        removes: "package.json"

    - name: "workflows » magento2 » project-install | run npm install in project source path when defined in .valet-sh.yml"
      ansible.builtin.shell: "source {{ current_home }}/.nvm/nvm.sh && nvm install {{ valet_sh_node_version }} && /usr/bin/env npm install"
      args:
        chdir: "{{ valet_sh_project_src_path }}"
        executable: /bin/bash
        removes: "package.json"
      when: valet_current_path != valet_sh_project_src_path

- name: "Block"
  when:
    - valet_sh_config.default_nvm is defined
    - valet_sh_config.default_nvm == "volta"
  block:
    - name: "workflows » magento2 » project-install | run npm install in current dir"
      ansible.builtin.shell: "{{ current_home }}/.volta/bin/npm install"
      args:
        chdir: "{{ valet_current_path }}"
        executable: /bin/bash
        removes: "package.json"

    - name: "workflows » magento2 » project-install | run npm install in project source path when defined in .valet-sh.yml"
      ansible.builtin.shell: "{{ current_home }}/.volta/bin/npm install"
      args:
        chdir: "{{ valet_sh_project_src_path }}"
        executable: /bin/bash
        removes: "package.json"
      when: valet_current_path != valet_sh_project_src_path
