##
#   Copyright 2024 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: systemd | daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: systemd | mysql57 | started
  ansible.builtin.systemd:
    name: mysql57
    daemon_reload: true
    state: started
  become: true

- name: systemd | mysql57 | stopped
  ansible.builtin.systemd:
    name: mysql57
    daemon_reload: true
    state: stopped
  become: true

- name: systemd | mysql57 | restarted
  ansible.builtin.systemd:
    name: mysql57
    daemon_reload: true
    state: restarted
  become: true

- name: systemd | mysql80 | started
  ansible.builtin.systemd:
    name: mysql80
    daemon_reload: true
    state: started
  become: true

- name: systemd | mysql80 | stopped
  ansible.builtin.systemd:
    name: mysql80
    daemon_reload: true
    state: stopped
  become: true

- name: systemd | mysql80 | restarted
  ansible.builtin.systemd:
    name: mysql80
    daemon_reload: true
    state: restarted
  become: true

- name: brew | vsh-mysql57 | started
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services start vsh-mysql57"

- name: brew | vsh-mysql57 | stopped
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services stop vsh-mysql57"

- name: brew | vsh-mysql57 | restarted
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services restart vsh-mysql57"

- name: brew | vsh-mysql80 | started
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services start vsh-mysql80"

- name: brew | vsh-mysql80 | stopped
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services stop vsh-mysql80"

- name: brew | vsh-mysql80 | restarted
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services restart vsh-mysql80"
