---

service:
  name:
    ubuntu: "vsh-valkey8"
    mac: "vsh-valkey8"
  scope:
    ubuntu: "user"
    mac: "user"
  provider:
    ubuntu: "systemd"
    mac: "container"

configuration:
  docker_image: "docker.io/valkey/valkey:8"
  ports:
    valkey: 6389
  base_path: "/usr/local/valet-sh/packages/valkey8"
