---

service:
  name:
    ubuntu: "vsh-valkey9"
    mac: "vsh-valkey9"
  scope:
    ubuntu: "user"
    mac: "user"
  provider:
    ubuntu: "systemd"
    mac: "container"

configuration:
  docker_image: "docker.io/valkey/valkey:9"
  ports:
    tcp: 6390
  base_path: "/usr/local/valet-sh/packages/valkey9"
