#
# valet.sh | db
#
# @author: "Philipp Dittert"
# @command: "db"
# @platform: macOS Ubuntu
# @description: "ls, create, drop, reset, import, export a mysql database"
# @usage: "valet.sh db <action>"
# @help:
#
# all commands will be executed on the default mysql database you selected
#
# ls: ls all databases
# valet.sh db ls
#
# create: create a new database
# valet.sh db create <dbname>
#
# drop: drops a existing database
# valet.sh db drop <dbname>
#
# reset: drops and creates a database
# valet.sh db reset <dbname>
#
# import: import a mysql database dump. Database will be created if it does not exist
# valet.sh db import <db-filename> <dbname>
#
# export: export a mysql database into given db-filename
# valet.sh db export <db-filename> <dbname>
#
#
---

- name: "db"
  hosts: local
  gather_facts: true
  vars:
    valet_action: "{{ cli.args[0] | default() }}"
    valet_current_path: "{{ lookup('env','OLDPWD') }}"
    valet_arg1: "{{ cli.args[1] | default() }}"
    valet_arg2: "{{ cli.args[2] | default() }}"
    valet_arg3: "{{ cli.args[3] | default() }}"
  roles:
    - valet-db
