#
# valet.sh | init
#
# @author: "Philipp Dittert"
# @command: "init"
# @platform: macOS Ubuntu
# @description: "creates a default .valet-sh.yml file in current directory
# @usage: "valet.sh init
# @help: "valet.sh -h init"


---

- name: "init"
  hosts: local
  gather_facts: true
  vars:
    valet_action: init
    valet_current_path: "{{ lookup('env','OLDPWD') }}"
  roles:
    - valet-init
