#
# valet.sh | init-instance
#
# @author: "Philipp Dittert"
# @command: "init-instance"
# @platform: macOS Ubuntu
# @description: "run init-instance command | Usage: valet.sh init-instance
# @help: "valet.sh -h db"
# @usage: "valet.sh init-instance

---

- name: "init-instance"
  hosts: local
  gather_facts: true
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "[sudo] Password"
      private: true
  vars:
    valet_current_path: "{{ lookup('env','OLDPWD') }}"
    valet_project_name: "{{ cli.args[0] | default() }}"
    valet_git_project_name: "{{ cli.args[1] | default() }}"
    valet_cli_opts: "{{ cli.opts | default([]) }}"

  roles:
    - sudo-permission-check
    - valet-init-instance
