#
# valet.sh | link
#
# @author: "Johann Zelger"
# @author: "Philipp Dittert"
# @command: "link"
# @platform: macOS Ubuntu
# @sudo: true
# @description: "Link current directory with given name | Usage: valet.sh link projectx php72"
# @usage: "valet.sh link <name> <php-version>"
# @help:
#
# EXAMPLES:
#
# link the current folder as projectx. When no php version is defined php71 will be used
# valet.sh link projectx
#
# link the current folder as projectx and use php73
# valet.sh link projectx php73
#
#
---
- name: "link"
  hosts: local
  gather_facts: true
  vars:
    valet_action: link
    link_name: "{{ cli.args[0] | default() }}"
    valet_current_path: "{{ lookup('env','OLDPWD') }}"
    php_version: "{{ cli.args[1] | default() }}"
  roles:
    - valet-link
