#
# valet.sh | phpstorm
#
# @author: "Philipp Dittert"
# @command: "phpstorm"
# @platform: macOS Ubuntu
# @description: "starts phpstorm with current directory as argument"
# @usage: "valet.sh phpstorm"
# @help:
#
# valet.sh phpstorm
#
---

- name: "phpstorm"
  hosts: local
  gather_facts: true
  vars:
    valet_current_path: "{{ lookup('env','OLDPWD') }}"
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "[sudo] Password"
      private: true
  roles:
    - sudo-permission-check
    - valet-phpstorm
