#
# valet.sh | restore
#
# @author: "Johann Zelger"
# @author: "Philipp Dittert"
# @command: "restore"
# @platform: macOS Ubuntu
# @description: "restore persistent instance resources (eg. db, media-files)"
# @usage: "valet.sh restore <(optional) instancebackup-identifier> <(optional) valet_restore_db_identifier>"
# @help:

---
- name: "restore"
  hosts: local
  gather_facts: true
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "[sudo] Password"
      private: true
  vars:
    valet_instancebackup_identifier: "{{ cli.args[0] | default() }}"
    valet_restore_db_identifier: "{{ cli.args[1] | default() }}"
    valet_current_path: "{{ lookup('env','OLDPWD') }}"
    valet_cli_opts: "{{ cli.opts | default([]) }}"
  roles:
    - sudo-permission-check
    - valet-restore
