#
# valet.sh | xdebug
#
# @author: "Johann Zelger"
# @author: "Philipp Dittert"
# @command: "xdebug"
# @platform: macOS Ubuntu
# @sudo: true
# @description: "enables xdebug for given php version e.g 7.2 7.3 | Usage: xdebug on 7.1"
# @usage: "valet.sh xdebug <state> <php-version>"
# @help:
#
# EXAMPLES:
#
# enable xdebug for php 7.2
# valet.sh xdebug on 7.2
#
# disable xdebug for php 7.2
# valet.sh xdebug off 7.2
#
---
- name: "xdebug"
  hosts: local
  gather_facts: True
  vars:
    valet_action: "{{ cli.args[0] | default() }}"
    php_version: "{{ cli.args[1] | default() }}"
    valet_current_path: "{{ lookup('env','OLDPWD') }}"
  roles:
    - valet-xdebug