---
- name: systemd | Podman | started
  ansible.builtin.systemd:
    daemon_reload: true
    name: podman
    state: started
  become: true

- name: systemd | Podman | stopped
  ansible.builtin.systemd:
    daemon_reload: true
    name: podman
    state: stopped
  become: true

- name: systemd | Podman | reload
  ansible.builtin.systemd:
    daemon_reload: true
    name: podman
    state: reloaded
  become: true

- name: systemd | Podman | restarted
  ansible.builtin.systemd:
    daemon_reload: true
    name: podman
    state: restarted
  become: true
