##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "ensure dnsmasq is installed"
  homebrew:
    name: dnsmasq
    state: present

- name: "ensure /etc/resolver directory exists"
  ansible.builtin.file:
    path: /etc/resolver
    state: directory
  become: true

- name: "ensure domain '{{ dnsmasq_domain }}' is handled by local dns"
  ansible.builtin.copy:
    dest: "/etc/resolver/{{ dnsmasq_domain }}"
    content: |
      nameserver 127.0.0.1
      port 5354
  become: true

- name: "ensure dnsmasq listens to port 5354"
  ansible.builtin.lineinfile:
    path: "{{ valet_sh_homebrew_prefix }}/etc/dnsmasq.conf"
    line: "port=5354"
    state: present
  become: true
  notify: brew | dnsmasq | restarted

- name: "ensure dnsmasq 'interfaces=' is set"
  ansible.builtin.lineinfile:
    path: "{{ valet_sh_homebrew_prefix }}/etc/dnsmasq.conf"
    regexp: "^interface="
    line: "interface="
    state: present
  become: true
  notify: brew | dnsmasq | restarted

- name: "ensure dnsmasq 'bind-interfaces' is set"
  ansible.builtin.lineinfile:
    path: "{{ valet_sh_homebrew_prefix }}/etc/dnsmasq.conf"
    line: "bind-interfaces"
    state: present
  become: true
  notify: brew | dnsmasq | restarted

- name: "ensure dns resolving for .{{ dnsmasq_domain }} domain is handled by dnsmasq"
  ansible.builtin.template:
    src: development-domain.conf.j2
    dest: "{{ valet_sh_homebrew_prefix }}/etc/dnsmasq.d/development-domain.conf"
  notify: brew | dnsmasq | restarted

- name: brew | dnsmasq | restarted
  ansible.builtin.shell: "{{ valet_sh_homebrew_bin }} services  restart dnsmasq"

- name: "Mark dnsmasq as installed in the services file"
  vsh_bundle_state:
    action: "installed"
    canonical_names: "dnsmasq"

- name: "Mark dnsmasq as enabled in the services file"
  vsh_bundle_state:
    action: "enabled"
    canonical_names: "dnsmasq"
