##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "check-vars | fail when no action was defined"
  ansible.builtin.fail:
    msg: "no action was defined"
  when: (valet_service_action is not defined) or (valet_service_action | length == 0)

- name: "check-vars | fail when action is not allowed"
  ansible.builtin.fail:
    msg: "action '{{ valet_service_action }}' is not allowed"
  when: valet_service_action not in valet_sh_service_allowed_actions

- name: "check-vars | normalize 'all' service name argument to --all option"
  ansible.builtin.set_fact:
    valet_cli_opts: "{{ (valet_cli_opts | default([])) + ['--all'] }}"
    valet_service_names: []
  when:
    - valet_service_names is defined
    - "'all' in valet_service_names"
    - "'--all' not in (valet_cli_opts | default([]))"

# FIXME: no user readable error message
- name: "check-vars | resolve multiple service names and configurations"
  vsh_bundle_resolver:
    name: ["{{ item }}"]
    current_os: "{{ current_os }}"
  register: vsh_resolvers
  loop: "{{ valet_service_names }}"
  when:
    - valet_service_names is defined
    - valet_service_names | length > 0

- name: "check-vars | create combined resolved service variable"
  ansible.builtin.set_fact:
    valet_canonical_names: "{{ vsh_resolvers.results | map(attribute='services') | flatten | map(attribute='canonical') | list + vsh_resolvers.results | map(attribute='packages') | flatten | map(attribute='canonical') | list }}"
    valet_all_services: "{{ vsh_resolvers.results | flatten | map(attribute='services') | flatten +  vsh_resolvers.results | flatten | map(attribute='packages') | flatten | list }}"
  when: vsh_resolvers is defined

- name: "block"
  when: valet_service_action != "list"
  block:
    - name: "check-vars | fail when no service name was given"
      ansible.builtin.fail:
        msg: "supplied no service names"
      when:
        - valet_service_names is not defined or valet_service_names | length == 0
        - "'--all' not in valet_cli_opts"

    - name: "check-vars | check if service is installed"
      vsh_bundle_install_state_info:
        name: "{{ item }}"
      register: service_installation_check
      when: valet_service_action != "list" and (valet_service_names is defined and valet_service_names | length > 0)
      loop: "{{ valet_canonical_names }}"

    - name: "check-vars | fail if service is not installed"
      ansible.builtin.fail:
        msg: "Services '{{ item }}' is not installed. Please install them first."
      when: item.kinds | length == 0
      loop: "{{ service_installation_check.results }}"

    - name: "check-vars | check if service state"
      vsh_bundle_service_state_info:
        name: "{{ item }}"
      register: service_state_check
      when: valet_service_names is defined and valet_service_names | length > 0
      loop: "{{ valet_canonical_names }}"

    - name: "actions » default | update valet_all_services with only the first service from loop when multiple versions are available"
      set_fact:
        valet_all_services: "{{ valet_all_services | flatten | groupby('name') | map(attribute='list.0') | list }}"
      when: valet_service_action == "default"
