---

service:
  name:
    ubuntu: "vsh-elasticsearch1"
    mac: "vsh-elasticsearch1"
  scope:
    ubuntu: "user"
    mac: "user"
  provider:
    ubuntu: "systemd"
    mac: "container"

configuration:
  docker_image: "docker.io/elasticsearch:1.7.6"
  arch: "amd64"
  limits:
    memory: "2g"
    cpus: "1"
  ports:
    http: 9201
  base_path: "/usr/local/valet-sh/packages/elasticsearch1"
  plugins:
    default_plugins:
      - name: "analysis-phonetic"
        url: "https://download.elasticsearch.org/elasticsearch/elasticsearch-analysis-phonetic/elasticsearch-analysis-phonetic-2.7.0.zip"
      - name: "analysis-icu"
        url: "https://download.elasticsearch.org/elasticsearch/elasticsearch-analysis-icu/elasticsearch-analysis-icu-2.7.0.zip"
    install_command: "/usr/share/elasticsearch/bin/plugin install"
    list_command: "/usr/share/elasticsearch/bin/plugin --list"
