---

service:
  name:
    ubuntu: "vsh-elasticsearch5"
    mac: "vsh-elasticsearch5"
  scope:
    ubuntu: "user"
    mac: "user"
  provider:
    ubuntu: "systemd"
    mac: "container"

configuration:
  docker_image: "docker.io/elasticsearch:5.6.16"
  arch: "amd64"
  limits:
    memory: "2g"
    cpus: "1"
  ports:
    http: 9205
  base_path: "/usr/local/valet-sh/packages/elasticsearch5"
  plugins:
    default_plugins:
      - name: "analysis-phonetic"
      - name: "analysis-icu"
    install_command: "/usr/share/elasticsearch/bin/elasticsearch-plugin install"
    list_command: "/usr/share/elasticsearch/bin/elasticsearch-plugin list"
