---

service:
  name:
    ubuntu: "vsh-elasticsearch6"
    mac: "vsh-elasticsearch6"
  scope:
    ubuntu: "user"
    mac: "user"

configuration:
  docker_image: "docker.io/elasticsearch:6.8.23"
  ports:
    http: 9206
    transport: 9306
  base_path: "/usr/local/valet-sh/packages/elasticsearch6"
  plugins:
    default_plugins: ["analysis-phonetic", "analysis-icu"]
    install_command: "/usr/share/elasticsearch/bin/elasticsearch-plugin install {{ name }}"
    list_command: "/usr/share/elasticsearch/bin/elasticsearch-plugin list"
