---

service:
  name:
    ubuntu: "vsh-elasticsearch6"
    mac: "vsh-elasticsearch6"
  scope:
    ubuntu: "user"
    mac: "user"
  provider:
    ubuntu: "systemd"
    mac: "container"

configuration:
  docker_image: "docker.io/elasticsearch:6.8.23"
  limits:
    memory: "2g"
    cpus: "1"
  ports:
    http: 9206
    transport: 9306
  base_path: "/usr/local/valet-sh/packages/elasticsearch6"
  plugins:
    default_plugins:
      - name: "analysis-phonetic"
      - name: "analysis-icu"
    install_command: "/usr/share/elasticsearch/bin/elasticsearch-plugin install"
    list_command: "/usr/share/elasticsearch/bin/elasticsearch-plugin list"
