---

service:
  name:
    ubuntu: "vsh-elasticsearch7"
    mac: "vsh-elasticsearch7"
  scope:
    ubuntu: "user"
    mac: "user"
  provider:
    ubuntu: "systemd"
    mac: "container"

configuration:
  docker_image: "docker.io/elasticsearch:7.17.7"
  limits:
    memory: "4g"
    memory_fraction: 50
    cpus: "2"
  ports:
    http: 9207
    transport: 9307
  base_path: "/usr/local/valet-sh/packages/elasticsearch7"
  plugins:
    default_plugins:
      - name: "analysis-phonetic"
      - name: "analysis-icu"
    install_command: "/usr/share/elasticsearch/bin/elasticsearch-plugin install"
    list_command: "/usr/share/elasticsearch/bin/elasticsearch-plugin list"
