---

service:
  name:
    ubuntu: "vsh-elasticsearch8"
    mac: "vsh-elasticsearch8"
  scope:
    ubuntu: "user"
    mac: "user"
  provider:
    ubuntu: "systemd"
    mac: "container"

configuration:
  docker_image: "docker.io/elasticsearch:8.19.18"
  limits:
    memory: "4g"
    memory_fraction: 50
    cpus: "2"
  ports:
    http: 9208
    transport: 9308
  base_path: "/usr/local/valet-sh/packages/elasticsearch8"
  plugins:
    default_plugins:
      - name: "analysis-phonetic"
      - name: "analysis-icu"
    install_command: "/usr/share/elasticsearch/bin/elasticsearch-plugin install"
    list_command: "/usr/share/elasticsearch/bin/elasticsearch-plugin list"
