name: CI

on:
  push:
    branches: [ 3.x ]
  pull_request:
    branches: [ 3.x ]

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Installing dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools git
          pip3 install -r requirements.txt
          ansible-galaxy collection install -r requirements.yml -p ./collections/

      - name: Run Ansible-Lint
        run: ansible-lint roles/